### ISSUE TITLE
04-authorization sample missing jwt-decode package

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-angular-samples#101]
The samplet mentioned gets stuck during execution due to a missing package:
![image](https://user-images.githubusercontent.com/15782359/38440078-1ff1be86-39ae-11e8-8454-ec14fe9dfea6.png)

**Comment by jimmyjames** [comment]
I'm not able to reproduce this; given the age of this issue, going to close. If you still experience it, please reopen.
