### ISSUE TITLE
localStorage being used

### ISSUE THREAD

**Issue by RibeiroAna** [auth0-samples/auth0-angular-samples#112]
Hello,

In this example you are using localStorage to keep the token, but the app becomes more vunerable because any script can access this token on `localStorage`. Maybe you should change to the approach used here: https://github.com/auth0-blog/auth0-web/blob/master/src/index.ts

Cheers,
Ana

**Comment by guilhermecgs** [comment]
Newbie question:
Your suggestion is to use an internal angular variable to store the token?
In that case, how can you share the token with other applications ? ex: single sign on

**Comment by RibeiroAna** [comment]
@guilhermecgs take a look at this tutorial I wrote: https://auth0.com/blog/full-stack-typescript-apps-part-2-developing-frontend-angular-apps/, in special the section: "Creating an Auth0 Angular Service"

**Comment by francescopeloi** [comment]
I think @guilhermecgs question is still open, If you keep the token in memory only, how would it work with Single Sign On?

**Comment by brunokrebs** [comment]
Hi guys. Actually, to achieve SSO, you are not supposed to share tokens among applications. Different applications should get different tokens. The SSO session is controlled by the _authorization server_ (for example, Auth0).

To illustrate, if you log into an application and then go to another application, while this second application issues a request to the _authorization server_ to get a new token (this is done by the `checkSession` function on the "Creating an Auth0 Angular Service" section mentioned by Ana), the server will know that the current browser is logged in, and will deliver a new token without requiring another authentication process.

**Comment by jimmyjames** [comment]
Originally reported issue of using localStorage has been fixed with https://github.com/auth0-samples/auth0-angular-samples/pull/142
