### ISSUE TITLE
There was an error fetching the SSO data.

### ISSUE THREAD

**Issue by spiritguide7** [auth0-samples/auth0-angular-samples#134]
package.json :   "auth0-js": "^9.4.1",
auth.service.ts :  public renewTokens(): void {
    this.auth0.checkSession({}, (err, authResult) => {
Allowed Web Origins:  <mydomain.com>

I am still getting a 404 when the app tries to get /user/ssodata, when the signin dialog appears.
It appears that I am able to signin, but I thought that this issue has been already fixed.
Can you suggest a way to prevent these errors?

Thanks

**Comment by stevehobbsdev** [comment]
Hey @spiritguide7, the sample app has been updated since this issue was raised. Could you try again and see if the new samples help with your particular issue?

I'll close this issue for now; if you're still having trouble, please feel free to continue the conversation.
