### ISSUE TITLE
Duplicated scheduleRenewal() in example

### ISSUE THREAD

**Issue by antyale** [auth0-samples/auth0-angular-samples#135]
Hello,

Example file: https://github.com/auth0-samples/auth0-angular-samples/blob/master/05-Token-Renewal/src/app/auth/auth.service.ts

In the following code:
```
    this.refreshSubscription = source.subscribe(() => {
      this.renewTokens();
      this.scheduleRenewal();
    });
```
the successful execution of the function `this.renewTokens()` already calls `this.scheduleRenewal()`, so this additional causes duplication of timers to renew the tokens.  One of them should be removed.

Thanks

**Comment by stevehobbsdev** [comment]
Hey @antyale, the sample app has been updated since this issue was raised - please feel free to check it out. I'll close this issue for now; if you're still having trouble, please feel free to submit another issue.
