### ISSUE TITLE
Cannot find modules: './auth0-variables' and 'auth0-lock'.

### ISSUE THREAD

**Issue by leongrin** [auth0-samples/auth0-angular-samples#137]
I am receiving the following errors when trying to run the app. How can I fix it?

ERROR in src/app/auth/auth.service.ts(2,29): error TS2307: Cannot find module './auth0-variables'.
Hash: 2904999ce1a6d26c4813
Time: 4620ms
src/app/auth/auth.service.ts(5,23): error TS2307: Cannot find module 'auth0-lock'.

**Comment by viccsjain** [comment]
If you clone the repo directly from Github, rename the auth0-variables.ts.example files in each of the
sample applications to auth0-variables.ts and provide the Client ID and Domain there. This file is located
in src/app/auth/.

Rename the file first and then run again.
