### ISSUE TITLE
05 - RenewTokens sample is broken

### ISSUE THREAD

**Issue by kaidokert** [auth0-samples/auth0-angular-samples#140]
First the renewToken call is broken/spelled wrong  :  https://github.com/auth0-samples/auth0-angular-samples/pull/138
 
Second, displaying the token expiry is broken, expiry field needs to be shown from memory as per 
PR https://github.com/auth0-samples/auth0-angular-samples/pull/136 or actually shown from localstorage as per https://github.com/auth0-samples/auth0-angular-samples/pull/139

Also it appears that CI isn't working at all, all PRs are failing for reasons unrelated to code changes

**Comment by mathiasconradt** [comment]
Same for me, getting this error when pressing the `Renew` button.

<img width="628" alt="Screen Shot 2019-03-28 at 8 02 17 AM" src="https://user-images.githubusercontent.com/295122/55136923-eba0af80-512f-11e9-848e-c1657af8752d.png">

**Comment by tomastalian** [comment]
Wrong method is called, 's' is missing at end  renewToken() -> renewTokens()

**Comment by stevehobbsdev** [comment]
@kaidokert Thanks for raising this. The samples have all now been rewritten and the old ones deprecated in favor of the new SDK.

However, I'd like to try and get this into the old samples (they've been tagged with `auth0js-9.10.4`) for those users still using the old stuff.
