### ISSUE TITLE
06-Single Sign On is missing documentation on Quickstart page

### ISSUE THREAD

**Issue by mathiasconradt** [auth0-samples/auth0-angular-samples#143]
The 06-Single Sign On sample is missing a documentation on the quickstart page at https://auth0.com/docs/quickstart/spa/angular2, there it's only showing samples 01 to 05.

The README is also missing the info that `http://localhost:3000` and `http://localhost:3001` needs to be added to the `Allowed Web Origins`. The same goes for the callback URL, where `http://localhost:3001/callback` should be added as well.

**Comment by stevehobbsdev** [comment]
@mathiasconradt I'm not sure why the documentation for this sample was never written.

However, all of the samples and documentation have been rewritten and are now live on auth0.com!
