### ISSUE TITLE
04 When I reload, I get back to the unlogin state

### ISSUE THREAD

**Issue by nishimura-yuji** [auth0-samples/auth0-angular-samples#148]
If you reload your browser after logging in, you will not be logged in.

I want to stay logged in until the user logs out.

Is there a solution?

**Comment by stevehobbsdev** [comment]
@nishimura-yuji How are you logging into your app, are you using a social provider such as Google, or username/password?

**Comment by nishimura-yuji** [comment]
@stevehobbsdev 
Thank you for your reply.

I use both.

**Comment by stevehobbsdev** [comment]
@nishimura-yuji I would expect that behavior if you're using the Google connection with the development keys (see [social connection caveats](https://auth0.com/docs/connections/social/devkeys))

The samples have just been updated using our [new JavaScript SDK](https://github.com/auth0/auth0-spa-js) - could you try these and let me know if they work better for you?

**Comment by webcourse-ng** [comment]
I wonder if I've the same issue. When I refresh the page, I once again see the Login button. But, it doesn't work. An error pops up in the console: Cannot read property 'loginWithRedirect' of undefined
TypeError: Cannot read property 'loginWithRedirect' of undefined
    at NavBarComponent.<anonymous> (nav-bar.component.ts:32)

I figure, something seems to be aware that there is an active session. As a result, some code that fires the first time doesn't fire the second time around. This holds true for the Angular package I downloaded yesterday from the Auth0 Setup page, as well as my app into which I've integrated the logic from the former.

**Comment by stevehobbsdev** [comment]
@webcourse-ng That exception—while not immediately clear—_usually_ points to a configuration problem.

Can you look at the network trace when you reload the page? When the page loads, you should see a call out to `/authorize` on `<your domain>.auth0.com`. If there's a problem, that call will fail and if you check the response, you might see an Auth0 error page in there. Might give us a clue as to what's going on.

FYI if that call fails, then the Auth0Client object doesn't get created properly, hence the `undefined` error you're getting.

**Comment by webcourse-ng** [comment]
Thanks for the quick reply, stevehobbsdev. You're right: the call to authorize fails with a reload, with an error 400. I get the OOPS page with the sad blue face for the result of this call. It contains a link to see technical details of the error, but that link doesn't work (didn't expect it to in this case, nonetheless, I'm left with no additional details.)

The difference in the calls are: 

- unique to the second call nonce, code_challenge, code_challenge_mode each show up twice in the second and failing call. their contents appear identical.
- properties that show up twice in the second call, but are also passed (just once each) in the succeeding initial call are prompt, and auth0Client. here again, the doubled up properties in the failed call have the same values.
- values that differ between the first successful call and second failing call are response_mode (successful call has query as value, failing call's value is web_message). state, nonce, code_challenge also differ, and all appear to be encrypted values (not sharing these here out of security concerns.)

Appreciate any thoughts on how to fix this.

**Comment by webcourse-ng** [comment]
Found the error in the logs, 'Silent Auth Failed'. Looks like an invalid origin problem. Will post on what I find.

**Comment by webcourse-ng** [comment]
The silentauth error said 'The specified redirect_uri 'http://localhost:4200/callback' does not have a registered origin.' Which it did. But after reading around, I tried using http://localhost:4200 - no end backslash, no path. That fixed it! Thank you, stevehobbsdev!

**Comment by stevehobbsdev** [comment]
@webcourse-ng No problem!
