### ISSUE TITLE
Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by PBarnard** [auth0-samples/auth0-angular-samples#154]
Hey, I'm getting the error "Cannot read property 'close' of undefined" after logging in successfully using a Microsoft social account.

This is an Angular 8 app and I've just gone through the Getting Started tutorial using auth0-spa-js.

I don't get this error when signing in using username/password.

Also, this only occurs on the first login of the application. If I logout then back in multiple times I don't see the error.

![image](https://user-images.githubusercontent.com/14309231/60458383-651bd280-9c36-11e9-994c-72871524d640.png)

**Comment by stevehobbsdev** [comment]
@PBarnard Do you have a repo for this I can take a look at?

**Comment by PBarnard** [comment]
Hey Steve, sadly no, working on a client's private repo at the moment. I'll have a look through the sample app in the morning and see if I can spot anything obvious that I might have missed.

**Comment by PBarnard** [comment]
@stevehobbsdev I just cloned and ran the sample angular app and can't recreate the issue so it was a problem with my code. I think it might be due to me doing:

`await this.auth0Client.loginWithRedirect({ redirect_uri: `` });`

instead of this as done in the sample:

`await this.auth0Client.loginWithRedirect({ redirect_uri: `${window.location.origin}/callback` });`

So, all good :)

**Comment by stevehobbsdev** [comment]
@PBarnard Glad you got it sorted!
