### ISSUE TITLE
Persist login between refreshes

### ISSUE THREAD

**Issue by ChaudhryAtif** [auth0-samples/auth0-angular-samples#162]
Similar to this: [https://community.auth0.com/t/persisting-login-between-refreshes/22675](url)

I am using the latest sdk.

To experience:

- Clone the repo, update credentials, and run
- Login so you see authenticated navbar
- Refresh, and you will see unauthenticated navbar for a few seconds because info is still being fetched from Auth0.

Previously we could get + store info from authResult and fetch from local storage and compare, This url [https://auth0.com/docs/security/store-tokens]() says not to store them in local storage, and to fetch each time. But this leads to awful user experience if we have to flicker between unauthenticated UI until fetch is complete.

How can this be resolved?

**Comment by stevehobbsdev** [comment]
Thanks for raising this @ChaudhryAtif. Really the sample should show neither the unauthenticated UI nor the authenticated UI until the authentication state can be determined. That way you wouldn't get the "flicker" effect.

So initially both the login and logout/profile UI would be hidden until the result comes back from Auth0. You could always store some more local state in your own apps that indicates login status, as long as you can reliably keep them in sync. That's very specific to your own scenario, however.
