### ISSUE TITLE
callback url keeps loading

### ISSUE THREAD

**Issue by padhumailin** [auth0-samples/auth0-angular-samples#163]
after login with google account, redirected to localhost callback url with Login link in navtab.
And this callback url is keeps spinning. How to fix this?

vendor.js:44320 ERROR Error: Uncaught (in promise): Error: Invalid algorithm

**Comment by stevehobbsdev** [comment]
Hi @padhumailin, this is down to a configuration problem with your Auth0 app. The new Auth0 SDK only supports the RS256 signing algorithm.

To fix it, open your [Auth0 dashboard](https://manage.auth0.com), open the application that you're connecting to, and under "advanced settings" you can change the signing algorithm to RS256.

Hope that helps!

**Comment by padhumailin** [comment]
Thank steve... it works
