### ISSUE TITLE
Update 01-Login README.md to include workaround for Invalid algorithm error

### ISSUE THREAD

**Issue by pgoldtho** [auth0-samples/auth0-angular-samples#171]
Following the quickstart setup instructions (https://auth0.com/docs/quickstart/spa/angular2) results in an Invalid algorithm error (see screenshot below).  The workaround for this is described in https://github.com/auth0-samples/auth0-angular-samples/issues/163. 

![Screen Shot 2019-08-17 at 12 09 03 PM](https://user-images.githubusercontent.com/13651001/63214575-c36a1b00-c0e7-11e9-8d51-fa438f15a705.png)

Also, it would be nice if the readme included the setup instructions from the quickstart page

**Comment by kmaida** [comment]
Applications created in the Auth0 dashboard have RS256 selected as the algorithm by default. An algorithm mismatch would occur if the application is legacy, or if it was manually changed to another algorithm by the developer. I can add a note in the README about this.

**Comment by pgoldtho** [comment]
I guess the Angular demo must be a legacy app.  I was following the hello world tutorial.  I don't believe I changed anything

**Comment by kmaida** [comment]
If this wasn't already enabled, then yes, your tenant and application were most likely created before this became the default setting for all new apps. We apologize for the confusion this may have caused and will add a note to the README. Thanks for your suggestion and patience!

New applications created in the Dashboard now have advanced settings that look like this by default (OIDC Conformant selected, with `RS256`):

![image](https://user-images.githubusercontent.com/1884525/64195477-92137e00-ce4f-11e9-9a63-aca9abbac8d1.png)

**Comment by kmaida** [comment]
Hey @pgoldtho, it's just been brought to my attention that, as of recently, we are experiencing an issue where the default application in new tenants is not being set to OIDC conformant / RS256 as normally is expected. 

We're working on a resolution now, but changing the setting manually will also solve your issue in the meantime!
