### ISSUE TITLE
Async-await alternative

### ISSUE THREAD

**Issue by ChaudhryAtif** [auth0-samples/auth0-angular-samples#173]
Is it possible to get promise-based (async-await) alternative to the current [auth service](https://github.com/auth0-samples/auth0-angular-samples/tree/master/02-Calling-an-API/src/app/auth/auth.service.ts), or even a full-fledged example using await-async just like Observables?

I found [auth service](https://github.com/auth0-samples/auth0-angular-samples/blob/new-sdk/03-Calling-an-API/src/app/auth/auth.service.ts) in `new-sdk` branch, but looks like it's half baked.

**Comment by kmaida** [comment]
Hello! We do not recommend using an async/await approach with the Angular sample, as the Angular framework itself is built with observables. Using async/await goes against a canonical implementation and you may experience challenges integrating with the Angular platform if you do not use the observable-based approach.

However, you can see an iteration using async/await from this commit: https://github.com/auth0-samples/auth0-angular-samples/commit/e99fc18d6d888d719d84c69a54a29c13874403db

Please be aware that the **async/await Angular implementation is not our recommended approach and we cannot support issues that may arise as a result of using that strategy**; but you're welcome to try it out.
