### ISSUE TITLE
localAuthSetup() seems not to be working properly

### ISSUE THREAD

**Issue by martajedrecka** [auth0-samples/auth0-angular-samples#174]
Hello,

the problem exists in both demo apps 01-Login and 02-Calling-an-API.
Login procedure works perfectly fine, after I'm logged in I can see profile page, information about currently logged in user. But when I refresh the page, all I have is a blank page (see screenshot) 
![image](https://user-images.githubusercontent.com/15836906/64712210-1a7ec800-d4bb-11e9-8c15-cf48fff17cc7.png)
the page is white because in home component (src/app/pages/home/home.component.html)  we have 
`<div class="container" *ngIf="auth.auth0Client$ | async">` 
moreover, properly loggedIn is null but in localAuthSetup() it should be setup either to true or false

I use Auth0 hosted page. Login with email and password (no social providers)

How to reproduce: 

- clone the app
- login 
- refresh the page
- see the blank page no matter if it home or profile page 

I used to work with auth0 on react app and there were no such issues. The token is saved to the local storage and from there function checking authorization takes it and do the checks.

**Comment by martajedrecka** [comment]
I found a solution in here: https://github.com/auth0/auth0-spa-js/issues/209

**Comment by stevehobbsdev** [comment]
Glad you found a solution @martajedrecka!
