### ISSUE TITLE
/Callback fails when run from prod build

### ISSUE THREAD

**Issue by developeer** [auth0-samples/auth0-angular-samples#177]
The callback fails since it is not captured by angular and sent to back to webserver.  
This works in development mode but not in prod build. 

using nodejs http-server but have reproduced with golang http.

ng build --prod
cd dist/auth0-angular-samples
http-server ./

the login prompts but then get blank page (404 page not found) since the /callback is sent to the backend webserver instead of being captured by angular.  

Had this been tested in a prod build?

-Edgardo

**Comment by kmaida** [comment]
Hi @developeer, thanks for bringing this to our attention, I am working on resolving this now.

**Comment by developeer** [comment]
Hi Kim,  Thank you.  If you need more information let me know.

I was running on windows 10 with node version 12.11.

-Edgar

________________________________

**Comment by kmaida** [comment]
Hi @developeer. The sample for Calling an API had a production server provided which passed routing to the backend which enabled the `/callback` route to work on production. However, I've now updated the samples so that they will work in a test prod build regardless of this.

**Comment by developeer** [comment]
HI Kim, Thank you for the quick turnaround.

I am still having an issue.  If you run the project with ng server -o. It works.  I see that the redirect uses /?code instead.  (only works in chrome.  Firefox gets an error invalid request).

If I do an ng build –prod which puts the project in the dist folder.

I cd into dist/login-demo

I previously install the http-server npm package with npm install http-server -g

I run the the site with http-server ./ -p 4200   ( I change the port because that is the port I have auth0 configured to).

The site comes up, I click on login, I enter the information and click login (auth0).

On redirect of the /?code url I get an error in the browser.

If you run the example without using the angular web server, it does not work.

Maybe this is outside of the scope of this project but I am trying to get this work with my angular 8/auth0 and golang server and I am getting the same problems as running the sample with a different web server.

I am going to test the 02 project next.



[cid:image001.png@01D58F10.85C69390]

Screenshot of webserver
[cid:image004.png@01D58F11.4BCFE730]

________________________________

**Comment by developeer** [comment]
Hi Kim,

I tried to run the 02 project but it does not compile.
I run ng serve -o and I get

The Auth0Client is in the typings/src/ folder not the typings folder.

[cid:image003.png@01D58F13.AC3C20F0]


________________________________
