### ISSUE TITLE
filter routing events by constructor.name doesn't work in production

### ISSUE THREAD

**Issue by luisrudge** [auth0-samples/auth0-angular-samples#18]
https://github.com/auth0-samples/auth0-angular-samples/blob/91fcef7e374ef79fffff322853525a1669194bfe/05-Authorization/src/app/auth/auth.service.ts#L58

This won't work in production mode of angular because the class name is changed.

Consider this code:

```js
this
  .router
  .events.subscribe((e) => {
    console.log(e.constructor.name);
  });
```

When you run in DEV mode (`ng serve`), you get this:
<img width="648" alt="screen shot 2017-03-23 at 19 46 40" src="https://cloud.githubusercontent.com/assets/941075/24273524/98a08c7c-1001-11e7-904c-513b412d6110.png">

But when you run in PROD mode (`ng serve --prod`), you get this:
<img width="648" alt="screen shot 2017-03-23 at 19 47 22" src="https://cloud.githubusercontent.com/assets/941075/24273526/9a5b1c80-1001-11e7-8a80-2435690ab12b.png">

**Comment by frederikprijck** [comment]
@luisrudge I've created a PR which got merged in for sample `01`, see: https://github.com/auth0-samples/auth0-angular-samples/pull/22 .

Basicly I've replaced `constructor.name` with `instanceof`.

**Comment by chenkie** [comment]
Fixed in latest samples

**Comment by sebastiangseijo** [comment]
I have faced this problem with --prod and --aot and the solution i have found was this:
i modified production.js so constructor.name can give you the correct name and not a simple letter.

node_modules/@angular/cli/models/webpack-configs/production.js

   ...
new webpack.optimize.UglifyJsPlugin({
   ...
   mangle: { screw_ie8: true, keep_fnames: true }, /* added keep_fnames: true so SomeClass.constructor.name works */
   ...
})

**Comment by frederikprijck** [comment]
@sebastiangseijo Keeping the function names isn"t what you want to be doing for production builds.

I think the auth0 api regarding this has changed, but I guess @chenkie can tell you that for sure.
If not, have a look at [my comment](https://github.com/auth0-samples/auth0-angular-samples/issues/18#issuecomment-290839227) explaining you how to get around this issue.

**Comment by chenkie** [comment]
@sebastiangseijo the key is to use `instanceof`. Have you tried that?

**Comment by tarasshpek** [comment]
@sebastiangseijo unforatunatelly your workaround doesn't work for Angular CLI v6, but I've found similar solution here: https://stackoverflow.com/a/50557403/8315708
