### ISSUE TITLE
canActivate: [AuthGuard] - default route not waiting for Auth to complete  

### ISSUE THREAD

**Issue by turkingj** [auth0-samples/auth0-angular-samples#181]
Say we want to protect all routes including the home component

`
{
    path: '',
    component: HomeComponent,
    canActivate: [AuthGuard]
  }
`

On testing this, the login/logout functionality ends up in a loop. If the default redirect is '/ ' it constantly redirects back to Auth0 Universal login page. Looking at the old example with the callback component, its not protected and gives the login process time to complete?

With the new code the `this.localAuthSetup()` and `this.handleCallback()` are called from the AuthService constructor maybe the AuthGuard is firing before this.localAuthSetup() and this.handleCallback() have time to complete?

**Comment by turkingj** [comment]
After adding a delay to the AuthGuard code, it seems to be working as expected...

```js
canActivate(
    route: ActivatedRouteSnapshot,
    state: RouterStateSnapshot,
  ): Observable<boolean> | Promise<boolean | UrlTree> | boolean {
    return this.auth.isAuthenticated$.pipe(
      delay(1000),
      tap(loggedIn => {
        if (!loggedIn) {
          this.auth.login(state.url);
        }
      }),
    );
  }
```

So it seems the first route hit after the Auth0 universal login only works if not protected with an AuthGuard.

**Comment by tomIQME** [comment]
Had the same problem. Seems to work with a delay.

**Comment by wimagee** [comment]
Also spent some time chasing my tail on this one. Did a workaround with a non guarded home route which is working adequately but this really needs sorted or at least some explanation in the docs.

**Comment by Padagi** [comment]
I had the same problem. Adding a delay helped a lot!

It seems that this can actually cause a long delay during login that is sort of hard to track down. For me it caused login times of 15-20 seconds in some cases, where AuthGuard is redirection to this.auth.login repeatedly until the auth completes before AuthGuard is called.

isAuthenticated$ should be blocked from returning an in-flight authentication if auth is in progress and just pending authComplete$ to finish.

**Comment by turkingj** [comment]
Instead of depending on the delay, I added a boolean flag to the auth service, to see if the this.handleAuthCallback() had completed and then checked for this flag within the AuthGuard

**auth.service.ts**
``` ts
  // Create subject and public observable for handleAuthCallback status
  private handleAuthCallbackCompleteSubject$ = new BehaviorSubject<boolean>( false);
  handleAuthCallbackComplete$ = this.handleAuthCallbackCompleteSubject$.asObservable();

  private handleAuthCallback() {
    // Call when app reloads after user logs in with Auth0
    const params = window.location.search;
    if (params.includes('code=') && params.includes('state=')) {
      let targetRoute: string; // Path to redirect to after login processed
      const authComplete$ = this.handleRedirectCallback$.pipe(
        // Have client, now call method to handle auth callback redirect
        tap(cbRes => {
          // Get and set target redirect route from callback results
          targetRoute = cbRes.appState && cbRes.appState.target ? cbRes.appState.target : '/';
        }),
        concatMap(() => {
          // Redirect callback complete; get user and login status
          return combineLatest([this.getUser$(), this.isAuthenticated$]);
        }),
      );
      // Subscribe to authentication completion observable
      // Response will be an array of user and login status
      authComplete$.subscribe(([user, loggedIn]) => {
        this.handleAuthCallbackCompleteSubject$.next(true);
        // Redirect to target route after callback processing
        this.router.navigate([targetRoute]);
      });
    }
    this.handleAuthCallbackCompleteSubject$.next(true);
  }
```

**auth.guard.ts**
``` ts
export class AuthGuard implements CanActivate {
  constructor(private auth: AuthService) {}

  waitForHandleAuthCallbackToComplete(): Observable<boolean> {
    return this.auth.handleAuthCallbackComplete$.pipe(
      filter(complete => complete),
      take(1),
    );
  }

  canActivate(
    next: ActivatedRouteSnapshot,
    state: RouterStateSnapshot
  ): Observable<boolean> | Promise<boolean | UrlTree> | boolean {
    return this.waitForHandleAuthCallbackToComplete().pipe(
      switchMap(() =>
        this.auth.isAuthenticated$.pipe(
          tap(loggedIn => {
            if (!loggedIn) {
              this.auth.login(state.url);
            }
          }),
        ),
      ),
    );
  }
}``

@kmaida do you think this would be a valid fix to the problem ?

**Comment by fooock** [comment]
Thanks for the code @turkingj it seems to work, but, if I press F5 to reload the page, the server responds with a 403 error... any idea on this? Did you change anything in the `localAuthSetup` method?

**Comment by stevehobbsdev** [comment]
Thanks everyone for their comments.

I would like to highlight something that we have been working on which will totally replace these samples, which is a brand new [Auth0 SDK for Angular](https://github.com/auth0/auth0-angular). Instead of continuing to iterate on what is essentially a wrapper component inside the Angular SPA sample, we have extracted it into a new library in its own right, [just as we did for React](https://github.com/auth0/auth0-react).

So all of this wrapper code has been rewritten and packaged as a new library. We've also updated the [quickstart](https://auth0.com/docs/quickstart/spa/angular-next) and [the sample](https://github.com/auth0-samples/auth0-angular-samples/tree/update/new-sdk/Sample-01) to use this new SDK.

I would be very keen to hear of anyone who tries out the new SDK and whether it solves your problem or makes your experience with using Auth0 and Angular together easier. If you try it out, the best place to provide feedback is the [issue tracker on the new repository](https://github.com/auth0/auth0-angular/issues).

I'll close this for now as we'll not be iterating on the sample code further, but I'm excited to hear feedback on the new bits!

**Comment by adnfyz** [comment]
> Thanks for the code @turkingj it seems to work, but, if I press F5 to reload the page, the server responds with a 403 error... any idea on this? Did you change anything in the `localAuthSetup` method?
> 
> **Edit:**
> 
> It works, but my `redirect_uri` from `createAuth0Client` was not correct.... my bad, thanks for this solution!

Did it work for you? what did you keep in redirectI_uri? mine has dashboard?key='uniquekeyForDifferentuser"
