### ISSUE TITLE
Chrome: login does not persist after page refresh

### ISSUE THREAD

**Issue by lipidfish** [auth0-samples/auth0-angular-samples#190]
When using the Chrome browser the login function works perfectly, but when I refresh the page it seems to loose the authenticated state. I can click the login button again, and it brings me back to the authenticated state right away, without going through the login screen again.

I am seeing this happen with both social providers and Auth0 database users.

This appears not to be the case when using Firefox.

**Comment by stevehobbsdev** [comment]
Thanks for raising @lipidfish - does this work if you run your app in Incognito mode? Are you using any Chrome extensions which may block the ability to read third-party cookies?

**Comment by lipidfish** [comment]
Thank you for the reply @stevehobbsdev. 3rd party cookie setting is the culprit.

Indeed my Chrome browser is blocking 3rd party cookies, and it appears as if I can't change that (company laptop) Firefox, though, does not have that restriction. Odd.

**Comment by stevehobbsdev** [comment]
Glad to be of help!
