### ISSUE TITLE
The template and walkthrough does not work

### ISSUE THREAD

**Issue by kwakuduahc1** [auth0-samples/auth0-angular-samples#192]
After downloading the sample. I run the application and it takes me to the login page alright but I get a 401 when I attempt to login.

Many thanks.

**Comment by stevehobbsdev** [comment]
Hi @kwakuduahc1, 

Please ensure you have read the [accompanying quickstart docs](https://auth0.com/docs/quickstart/spa/angular2) and the [documentation for Auth0 SPA SDK](https://github.com/auth0/auth0-spa-js) about how the login flow works. This sounds like configuration, so please ensure that your Auth0 client is configured correctly.

Feel free to open (or reopen) another issue with more details about the problem. As much as you can, including:

- version of Angular
- version of Auth0 SPA SDK
- a small sample that reproduces the issue, if possible

**Comment by kwakuduahc1** [comment]
Hello, 

Thank you for your response. However, I just followed the documentation and did not modify any part of the application. I am saying when I run this template, I get an error saying unauthorized. It it may help, this is a screenshot.

![image](https://user-images.githubusercontent.com/11381582/84556307-3bf23600-ad11-11ea-8d93-6ffa81ded952.png)

Many thanks.

**Comment by kwakuduahc1** [comment]
The solution was found in the same issue somebody had filed in the React template. However, the option is disabled by default and requires trickery.

![image](https://user-images.githubusercontent.com/11381582/84556443-5aa4fc80-ad12-11ea-9b1b-e788b1a4f75e.png)

Change the app type then set the Token.. to None. Change the app type back to SPA and it should work.
