### ISSUE TITLE
Unused code

### ISSUE THREAD

**Issue by Alistair-Clough-A30001802** [auth0-samples/auth0-angular-samples#194]
https://github.com/auth0-samples/auth0-angular-samples/blob/6ab4b71611fa4604cee899cf3e18b5956f4a2929/01-Login/src/app/auth/auth.service.ts#L109

Line 109 from the example code doesn’t seem to use ‘user’ or ‘loggedIn’. What function do they serve?

authComplete$.subscribe(([user, loggedIn]) => {
// Redirect to target route after callback processing
this.router.navigate([targetRoute]);
})

**Comment by stevehobbsdev** [comment]
Thanks @Alistair-Clough-A30001802 , and apologies for the radio silence.

I think there is a case of some unused legacy code going on here. As you can see in the code, they aren't being used and could be removed.

We're about to rewrite the samples for Angular, so all this code you're looking at will disappear in favour of something much simpler.
