### ISSUE TITLE
Restoring Login State with Angular 9 and auth0-spa-js

### ISSUE THREAD

**Issue by ChrisFulstow** [auth0-samples/auth0-angular-samples#198]
Hi, I’ve been following the Angular quickstart to integrate Auth0 into my SPA app using the Google social connector. I can authenticate fine via Google and read the ID token claims. The problem is when I refresh the page, it doesn’t seem to be restoring the login state, and I need to login again. This behaviour seems to be the same in both my app and the Angular quickstart code.

How can I get my app to silently restore the user’s logged in state without prompting to re-authenticate?

**Comment by davidobrien1985** [comment]
duplicate of #197

**Comment by ChrisFulstow** [comment]
pingback https://community.auth0.com/t/restoring-login-state-with-angular-9-and-auth0-spa-js/47941/

**Comment by stevehobbsdev** [comment]
@ChrisFulstow You mentioned on the community issue that it works when you sign in with a username and password.

Auth0 has a limitation that, if you sign in with a social connection that uses Auth0's development keys, while _also_ using the _classic_ login experience, then silent authentication does not work. The SDK relies on silent authentication to log you back in on a page refresh.

If that's the case, are you able to try either:

- Specify your own application keys for the social providers you're using, or
- Use the new login experience

[This should hopefully give you some more info](https://auth0.com/docs/connections/social/devkeys#limitations-of-developer-keys)

**Comment by ChrisFulstow** [comment]
@stevehobbsdev legend, that's fixed it, cheers Steve. I created my own Google client ID and secret.
