### ISSUE TITLE
Auth0 Angular Interceptor setting req.body values to null on POST method

### ISSUE THREAD

**Issue by thecarlo** [auth0-samples/auth0-angular-samples#200]
I implemented the Angular SPA quickstart in a Angular 9 app (https://auth0.com/docs/quickstart/spa/angular2/02-calling-an-api#create-an-http-interceptor and https://github.com/auth0-samples/auth0-angular-samples/blob/master/02-Calling-an-API/src/app/auth/interceptor.service.ts)

The interceptor correctly sets the Authorization header for all HTTP method types.

However, for POST methods, the req.body values for all keys are set to null in the `this.auth.getTokenSilently$().pipe( ...` method

If I console.log the req.body before the `this.auth.getTokenSilently$().pipe( ...` method, the req.body has the expected values.

<img width="634" alt="interceptor-code" src="https://user-images.githubusercontent.com/5310264/91566777-7f128b80-e987-11ea-8c09-27bf56642c22.png">

<img width="1342" alt="interceptor-console" src="https://user-images.githubusercontent.com/5310264/91566789-85a10300-e987-11ea-8ca0-e9a28db01709.png">

```
import { Injectable } from '@angular/core';
import {
  HttpRequest,
  HttpHandler,
  HttpEvent,
  HttpInterceptor,
} from '@angular/common/http';
import { AuthService } from './auth.service';
import { Observable, throwError } from 'rxjs';
import { mergeMap, catchError } from 'rxjs/operators';

@Injectable({
  providedIn: 'root'
})
export class InterceptorService implements HttpInterceptor {

  constructor(private auth: AuthService) { }

  intercept(
    req: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {

    console.log('pre mergeMap req.body', req.body);

    return this.auth.getTokenSilently$().pipe(

      mergeMap(token => {

        console.log('mergeMap req.body', req.body);

        const tokenReq = req.clone({
          setHeaders: { Authorization: `Bearer ${token}` }
        });

        return next.handle(tokenReq);

      }),
      catchError(err => throwError(err))

    );

  }
}
```

**Comment by stevehobbsdev** [comment]
Thanks @thecarlo for the report. We are very shortly about to replace these samples with those that use a [brand-new SDK](https://github.com/auth0/auth0-angular). It has an HTTP interceptor built in, and I would be keen to find out if you experience the same when using that.

The updated quickstart and samples are linked to from that repo. The samples are just a branch of this very repository (check out the `new-sdk` branch).

Rather than patching the sample we have now with fixes, we're concentrating on getting the new content to you as quickly as possible.

If you try the new bits, can you let me know how you get on?

**Comment by thecarlo** [comment]
@stevehobbsdev I implemented the changes, but unfortunately the same problem persists.

The Auth header is now injected as I get results for GET methods.

However, logging from my Node API reveals that the req.body values for keys are still being set to null:

Logging from my Node API shown below
```
{"message":{"title":null,"done":false},"level":"info","timestamp":"2020-08-29T03:06:54.624Z"}
{"errors":{"title":{"name":"ValidatorError","message":"Path `title` is required.","properties":{"message":"Path `title` is required.","type":"required","path":"title","value":null},"kind":"required","path":"title","value":null}},"_message":"todo validation failed","level":"error","timestamp":"2020-08-29T03:06:54.625Z"}
{"message":"::1 - - [29/Aug/2020:03:06:54 +0000] \"POST /api/todo HTTP/1.1\" 500 55 \"http://localhost:4200/\" \"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36\"\n","level":"info","timestamp":"2020-08-29T03:06:54.625Z"}
```

**Comment by stevehobbsdev** [comment]
@thecarlo Did you manage to get to the bottom of this? The new samples and SDK have been released, but I haven't been able to reproduce what you're seeing.

**Comment by stevehobbsdev** [comment]
Closing for now, feel free to continue the conversation if you're still having issues.

**Comment by thecarlo** [comment]
Hi @stevehobbsdev unfortunately the issue still persists. I asked some colleagues to look at this and they have also reported the same issues.

**Comment by thecarlo** [comment]
Hi @stevehobbsdev unfortunately the issue still persists. I asked some colleagues to look at this and they have also reported the same issues.

Have decided to go the route of implementing our own auth solution instead.
