### ISSUE TITLE
/oauth/token: getting 401 response status

### ISSUE THREAD

**Issue by VinitTomar** [auth0-samples/auth0-angular-samples#201]
Followed this sample code line by line, still getting 401.
Respones payload is 
```
error: "access_denied"
error_description: "Unauthorized"
```

**Comment by stevehobbsdev** [comment]
@VinitTomar We have an issue with the default app that is created when you set up a new tenant.

Could you try it with a brand-new Single Page Application type, and ensure that the Token Endpoint Authentication Method setting is set to "None"?

Please see this thread for more info: https://github.com/auth0/auth0-spa-js/issues/539

**Comment by VinitTomar** [comment]
@stevehobbsdev It worked. Thanks
