### ISSUE TITLE
redirectUri does not work

### ISSUE THREAD

**Issue by manast** [auth0-samples/auth0-angular-samples#206]
I spent several hours debugging this problem in my own application, and finally I gave it a try with the sample app and indeed it is not working. 
How to reproduce:

1) Add ```http://localhost:4200/profile``` to the Allowed Callback URLs
2) Change ```environment.ts``` so that ```redirectUri``` points to ```http://localhost:4200/profile``` instead of pointing to ```window.location.origin```

Try to login, login succeeds but you are not redirected to the profile page, instead you are back on the page root.

**Comment by stevehobbsdev** [comment]
@manast Let me close this one and respond on the other issue that you've generated.
