### ISSUE TITLE
Dynamic configuration for AuthModule

### ISSUE THREAD

**Issue by diva-kia** [auth0-samples/auth0-angular-samples#207]
Due to the current setup of our application, we need to use dynamic external configuration to support multiple environments. However since Angular loads the module (AuthModule.forRoot()) first before the configuration, the configuration renders undefined. I need to be able to use AppConfig as the configuration for AuthModule just like this:

```
AuthModule.forRoot({
     domain: AppSettings.domain,
     clientId: AppSettings.clientId,
})
```

**Comment by frederikprijck** [comment]
Hi @diva-kia ,

This is being tracked as part of https://github.com/auth0/auth0-angular/issues/47 and we are working on a solution so you can dynamically configure the AuthModule.
