### ISSUE TITLE
Connection parameters

### ISSUE THREAD

**Issue by LZorglub** [auth0-samples/auth0-angular-samples#208]
In previous SDK i was able to send the connection parameters to specify the database connection.
How can i do that with this API ?

**Comment by frederikprijck** [comment]
You can specify `connection` when calling `loginWithRedirect`:

```
this.auth.loginWithRedirect({
  connection: 'CONNECTION ID'
});
```

The same goes for calling `loginWithPopup`:
```
this.auth.loginWithPopup({
  connection: 'CONNECTION ID'
});
```
