### ISSUE TITLE
Access token visibility

### ISSUE THREAD

**Issue by LZorglub** [auth0-samples/auth0-angular-samples#209]
In previous SDK the access token was not retain in local storage, i see that this SDK use the local storage.
Do we have options to hidde access token ?

**Comment by frederikprijck** [comment]
This library uses localstorage in an opt-in way.
The sample app in this repository does not use locsalstorage out of the box.

Local storage can be used by specifying the corresponding cachelocation:

```
AuthModule.forRoot({
   ...
  cacheLocation: 'localstorage',
}),
```

So if you do not specifiy this cacheLocation, localstorage **will not be used**.
