### ISSUE TITLE
Navigation items not getting hidden in other tab

### ISSUE THREAD

**Issue by nadeemy** [auth0-samples/auth0-angular-samples#211]
I am using the sample application which can be downloaded from Auth0 site with no modifications whatsoever. Once after login, I open the sample application in second tab. So, now I have two tabs open and the Navigation bar is showing "Home" and 
"External API". I logout from one tab, the page refreshes and updates the Navigation and shows "Home" only. The Login button reappears as expected. 
![Tab 1](https://user-images.githubusercontent.com/14071626/99654951-16681600-2a81-11eb-9b50-165f103658c6.JPG)

I open the second tab, the navigation isn't updated, it shows "Home" as well as "External API". I would expect that the "External API" menu would no longer be visible.  Moreover, I now click on "External API" menu, the URL gets updated to http://localhost:4200/external-api
![Tab 2](https://user-images.githubusercontent.com/14071626/99654982-22ec6e80-2a81-11eb-9abc-67e32e57f48d.JPG)

Shouldn't clicking on "External API", instead of updating the URL, redirect to the login page?

**Comment by frederikprijck** [comment]
> I open the second tab, the navigation isn't updated, it shows "Home" as well as "External API"

Did you refresh that second tab? There is nothing telling two different tabs about authentication changes.

**Comment by nadeemy** [comment]
> > I open the second tab, the navigation isn't updated, it shows "Home" as well as "External API"
> 
> Did you refresh that second tab? There is nothing telling two different tabs about authentication changes.

Refreshing the tab does work as expected. However, the "External API" nav item is conditionally shown using *ngIf="auth.isAuthenticated$ | async"

<li class="nav-item" *ngIf="auth.isAuthenticated$ | async">
	<a routerLink="external-api" class="nav-link">External API</a>
</li>

Should that not hide it in other tab without the need to refresh it?

Also, shouldn't  the AuthGaurd prevent the updation of the URL to http://localhost:4200/external-api when clicked once the user has already been signed out

{
    path: 'external-api',
    component: ExternalApiComponent,
    canActivate: [AuthGuard],
  },

**Comment by frederikprijck** [comment]
The isAuthenticated$ observable in Tab1 is not notified when authenciation state changes in Tab, so no the navigation item doesn't get hidden.

> Also, shouldn't the AuthGaurd prevent the updation of the URL to http://localhost:4200/external-api when clicked once the user has already been signed out

As the guard is using the isAuthenticated$ observable, the guard will not be able to catch this.

Even more, when you are not making use of local storage, multiple tabs result in multiple access token, one for each tab.
Logging out in one tab does not remove the access token in the other tab, so even API requests would continue working in that case.

If you application does use local storage, which I would not recommend if not needed, your Access Token will be revoked for all tabs and API calls will not work anymore.

**Comment by nadeemy** [comment]
We do indeed use the local storage in the real application. The issue that appears is that it tries to make an authorize call and properly gets back an error that Login is required but the application doesn't get redirected to the configured Logout URL and stays on the same page. The console does show the error like this:
![Login Error](https://user-images.githubusercontent.com/14071626/99681914-b1261c00-2aa4-11eb-9ae7-6017891af8b7.JPG)

**Comment by frederikprijck** [comment]
> but the application doesn't get redirected to the configured Logout URL

I do not understand why you would want to redirect to the logout URL when the user is not logged in ?

> The console does show the error like this:
What is throwing this error ? Can you give some more information and, preferably, show some code that is triggering this error?

I think the idea would be to catch the error and react accordingly. This is not something we can solve on the SDK level as every application has its unique behavior for this.

For example you could implement something like this yourself:

```
this.authService.getTokenSilently().pipe(
  catchError(err => this.router.navigateByUrl('/login')) // check the error for login required
)
```

**Comment by nadeemy** [comment]
Thank you @frederikprijck  for your patience and providing the guidance for fixing this. I was able to track down the place the origin of the "Login Required" error message and take the appropriate action based on that.
