### ISSUE TITLE
Clicking on “login” I see that the call to “this.auth.loginWithRedirect();” is made but nothing happens 

### ISSUE THREAD

**Issue by konradsopala** [auth0-samples/auth0-angular-samples#214]
Hey team! 

This is the feedback relayed from on of our Auth0 Community Forum users. Here's the reference: 

https://community.auth0.com/t/quickstart-angular-project-is-not-working/54997

Pretty much the issue as in the title. Here's the solution to the issue:

Modifying the contents of app.module.ts as follows solved the problem:
```
AuthModule.forRoot({
      domain: 'xxxxxxxxxxx.auth0.com',
      clientId: 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY',
      // ...env.auth,
      httpInterceptor: {
        ...env.httpInterceptor,
      },
    }),
```

Further feedback:

''I had not modified the API_IDENTIFIER in the auth_config.json. Those instructions are not included in your help page. Once I put that value in, the use of …env.auth worked.

Please update https://auth0.com/docs/quickstart/spa/angular/01-login to include instructions on how to replace the value for {API_IDENTIFIER} in auth_config.json''

**Comment by frederikprijck** [comment]
Hey, we will see how we can improve this.

I do want to add that this information is part of the quickstart: https://auth0.com/docs/quickstart/spa/angular/02-calling-an-api

> Finally, modify the configuration given to AuthModule.forRoot() to specify the **audience** and scope values required by the API you want to call, as well as the API routes that should be intercepted by AuthHttpInterceptor.

Even though this is not an identical match with how the code is structured in the sample application and I can see how that can be confusing.

**Comment by konradsopala** [comment]
Thanks a lot!
