### ISSUE TITLE
Auth0 Login is not working with routing strategy { useHash: true } in Angular 12

### ISSUE THREAD

**Issue by vinodifour** [auth0-samples/auth0-angular-samples#242]
Hello, 

I am trying to integrate Auth0 Login with Microsoft Office Word Add-in, The issue i'm facing is, I've to use
HashLocationStrategy in order to make my routing work in add-in iframe. But it seems like the auth0 login is not working with given routing strategy as it constantly returning false to my 'IsAuthorized$' Observable.

Also, I've checked with given  [auth0-angular-samples-Sample-01](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01) auth0 demo on git hub for browser angular application and it seem working fine, But when i tried to apply { useHash: true }  in my routing imports it prevents me from getting authenticated, So Please verify this issue and let us know if there any suggestion and  solution for the same.

For quick review of my demo code, here is the link: [Auth0 sample with HashLocationStrategy](https://ifourtechnolab-my.sharepoint.com/:f:/p/vimal/EkeISMygextIo8DU-TBJ7n8Ber1pkeJcbJc7VTvb50eYmg?e=SvskFk)

Any small help would be appreciated.
Thank you.

**Comment by frederikprijck** [comment]
I believe this is a bug in our SDK. Could you please open an issue on the SDK's repository https://github.com/auth0/auth0-angular.

Thanks!
