### ISSUE TITLE
Multiple projects(Applications) using only one time Auth0 Login authentication

### ISSUE THREAD

**Issue by sayemuddinkhan-mriirs** [auth0-samples/auth0-angular-samples#248]
I am using Auth0 for user authentication and I want to implement Single sign on in my several apps running individually. I am able to use this Angular auth0 sample app with auth0  universal login page but I am not sure how can I integrate my other projects running into this same sign on?

Please help, Any help or suggestions will be much appreciated.

Thanks you :)

**Comment by frederikprijck** [comment]
Hey @sayemuddinkhan-mriirs ,

SSO should work fine, here is an overview of how it works https://auth0.com/docs/configure/sso.

In Angular, this works in the same way:

- User goes to your first application
- Application checks on startup if a user is logged in, if not you redirect to Auth0 using `loginWithRedirect`
- User is asked for their credentials
- User is returned to your application and is authenticated

- User goes to your second application
- Application checks on startup if a user is logged in, if not you redirect to Auth0 using `loginWithRedirect`
- User is not asked for their credentials, but instantly return to your application and is authenticated.

This flow is needed initially on all different applications. Once every application has retrieved an authenticated user, our SDK will set a cookie for that domain and will silently check for a session with Auth0 on page refresh.
