### ISSUE TITLE
Lock version outdated

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-angular-samples#26]
Lock version is outdated on the following sections:
   - 01-login
   - 03-session-handling
   - 04-user-profile
   - 05-linking-accounts
   - 06-rules
   - 07-authorization
   - 09-mfa
   - 10-customizing-lock

In the  `index.html`  file, as shown on the followind picture:
![image](https://cloud.githubusercontent.com/assets/15782359/25446431/7e6212fc-2a7f-11e7-8f3a-1b52784fbe12.png)

Also, on the `README.md` file as shown here:
![image](https://cloud.githubusercontent.com/assets/15782359/25446644/2a412f9a-2a80-11e7-82c0-32ce127ce1cb.png)

The latest version is **V10.14**.

Ticket: AUTH-3348

**Comment by chenkie** [comment]
Fixed thanks
