### ISSUE TITLE
Sample signUpAndAuthorize Call

### ISSUE THREAD

**Issue by picosam** [auth0-samples/auth0-angular-samples#28]
Can you please provide an example on how to use `signUpAndAuthorize`?

**Comment by chenkie** [comment]
The recommended approach for now (just updated in the sample) is to use `signup` and `login` inside the callback: https://github.com/auth0-samples/auth0-angular-samples/blob/embedded-login/02-Custom-Login-Form/src/app/auth/auth.service.ts#L35-L48

Is there a specific need to use `signupAndAuthorize`?

**Comment by picosam** [comment]
I want to acknowledge the fact that the user has signed up already; I save the token in `localStorage` and use it again to call `userInfo` every time `AuthGuard`'s `canActivate` fires. If `email_verified` is not true, I redirect the user to a page that alerts him that their email has not yet been verified.

**Comment by chenkie** [comment]
Gotcha. You should be able to accomplish that with `signup` though, no?

**Comment by picosam** [comment]
It's just that when I look at the [docs](https://auth0.com/docs/api/authentication#signup), I see that `signup` does not return any tokens.

**Comment by chenkie** [comment]
True but you can use `login` in the call back to get the tokens, after which you can continue to ping `/userinfo` to check whether the email is verified. Does that work?

**Comment by picosam** [comment]
I'm sure it does, but what advantage does making two network trips instead of one give me?

**Comment by chenkie** [comment]
We'll be adding another method in to do it in one shot later, but the advantage is that the `login` method uses a cross-origin flow which we recommend for added security.
