### ISSUE TITLE
HS256 not supported

### ISSUE THREAD

**Issue by namel** [auth0-samples/auth0-angular-samples#30]
authentication fails, console indicates error:
 `"invalid_token" "Algorithm HS256 is not supported. (Expected algs: [RS256])"`

I found a workaround to this on issue: https://github.com/auth0/auth0.js/issues/303

but since this is a sample app, it should work right out-of-the-box

**Comment by chenkie** [comment]
Hi @namel 

Which sample in particular did you get the error in?

**Comment by namel** [comment]
it was on 01-Login

**Comment by chenkie** [comment]
Did you make any changes to the config in the `AuthService`? The reason I ask is that with the configuration that's there, it should force the ID token to be signed with RS256.

**Comment by namel** [comment]
No I did not.  After applying the workaround described above, I'm now getting an error that the token is signed in the future, even though my time is set automatically over the network.

This could be related do my environment though?  I'm on the Linux Subsystem for Windows.  Another thing that fails on this environment is that the uniqid package fails (see https://github.com/Microsoft/BashOnWindows/issues/468)

**Comment by chenkie** [comment]
for issues with system clocks you can add the `leeway` option in your `WebAuth` config. I'd start with 5 seconds.

```ts
auth = new auth0.WebAuth({
  // ...
  leeway: 5
});
```

**Comment by chenkie** [comment]
Also can you check which "Client Type" you have set in the clients settings in the Auth0 dashboard?

**Comment by ArtemAlekhin** [comment]
I have a similar problem with an example 01-Login. I just downloaded the sample, rename file auth0-variables.ts.example to auth0-variables.ts  and defined the variables (clientID, domain) in the auth0-variables.ts file. After the login I get a message in console "Algorithm HS256 is not supported. (Expected algs: [RS256])". Client Type is Non Interactive Client

**Comment by ssaso** [comment]
@namel choosing single-page-app in "Client Type" solved my problem

**Comment by sinedsem** [comment]
Yes!! To solve `invalid_token` error with description 
`Algorithm HS256 is not supported. (Expected algs: [RS256])`
one should set "Client Type" at https://manage.auth0.com/#/clients to Single Page Application

**Comment by schwer** [comment]
Why does this work?
