### ISSUE TITLE
JWT must have 3 parts

### ISSUE THREAD

**Issue by Steven-Harris** [auth0-samples/auth0-angular-samples#32]
I am getting the following error and I am not quite sure how to debug/fix it. Thoughts?

```
Error: JWT must have 3 parts
    at JwtHelper.decodeToken (angular2-jwt.js:236) [angular]
    at JwtHelper.getTokenExpirationDate (angular2-jwt.js:246) [angular]
    at JwtHelper.isTokenExpired (angular2-jwt.js:255) [angular]
    at tokenNotExpired (angular2-jwt.js:274) [angular]
    at AuthHttp.requestWithToken (angular2-jwt.js:107) [angular]
    at DeferSubscriber.factory (angular2-jwt.js:146) [angular]
    at DeferSubscriber._callFactory (DeferObservable.js:92) [angular]
    at DeferSubscriber.tryDefer (DeferObservable.js:85) [angular]
    at new DeferSubscriber (DeferObservable.js:81) [angular]
    at DeferObservable._subscribe (DeferObservable.js:71) [angular]
    at DeferObservable.Observable._trySubscribe (Observable.js:57) [angular]
    at DeferObservable.Observable.subscribe (Observable.js:45) [angular]
    at MapOperator.call (map.js:54) [angular]
    at Observable.subscribe (Observable.js:42) [angular]
```

**Comment by chenkie** [comment]
it sounds like you probably have an opaque access token in local storage instead of a JWT. Can you check what you have for your `access_token`? 

Which sample are you trying? Have you configured your `audience` to use your API identifier?

**Comment by Steven-Harris** [comment]
Hey @chenkie thanks for your help, I have verified that the audience is correct and my api that has the same audience is working.
I am unfamiliar with checking the access_token. What should I do to check it?

Thanks,

**Comment by Steven-Harris** [comment]
Ok, I looked at my access_token in localstorage and  you suspected right. The access token is a short string about 14 characters

**Comment by Steven-Harris** [comment]
What do I need to do to set the access_token with the JWT one?

I am using the same pattern as example 1

```
 localStorage.setItem('access_token', authResult.accessToken);
 localStorage.setItem('id_token', authResult.idToken);
```

**Comment by chenkie** [comment]
those are the correct lines. The `access_token` you get back will either be a 14 char string like that, or a JWT. It's a JWT if you have a valid `audience` set as your API identifier.

What do you have set as your `audience`?

**Comment by Steven-Harris** [comment]
I have the following in my auth0.WebAuth object
``` audience: 'https://api.stevenharrisdev.com',```

**Comment by chenkie** [comment]
Hmm you should be getting a JWT then. Maybe try creating another test API in Auth0 and see if anything changes. Otherwise we'll probably need to route you to support and get you to send in a HAR file.

**Comment by Steven-Harris** [comment]
Is there any way I can get a jwt token as my access_token or is there a reason I am not?  I have a jwt for my id_token but not my access_token.

**Comment by chenkie** [comment]
The `id_token` will always be a JWT. The `access_token` should be as well if you have your `audience` set to your API identifier. Did you try with a different (new) API? Also, just for good measure, try going to the OAuth settings for your client and make sure that the OIDC Conformant switch is flipped to on.

**Comment by Steven-Harris** [comment]
oh ok, 
Yeah I tried with a new api and it didn't do anything different. Let me check the OIDC Conformant. - This is configured in Auth0 settings page right?

**Comment by Steven-Harris** [comment]
Ok "OIDC Conformant", was not turned on but I need to figure out how to fix my call back after I login. It is redirecting to my oauth domain and not my localhost for some reason.

**Comment by chenkie** [comment]
What do you have set as your callback?

I should have asked earlier, but are you using Auth0Lock or auth0.js for your project?

**Comment by Steven-Harris** [comment]
Auth0-js.

I have my local host set as my call back. But for some reason it redirects
me to an error page at stevenharrisdev.auth0.com/login/callback

**Comment by Steven-Harris** [comment]
Also I am running angular 4

**Comment by chenkie** [comment]
Ah ok--do you have your callback route set as an Allowed Callback URL in your client settings?

**Comment by Steven-Harris** [comment]
Yep. I have double checked that all possible routes in the callback. I have
to turn oidc back to off for it to work

**Comment by chenkie** [comment]
Ok, but you're getting a JWT access token now?

**Comment by Steven-Harris** [comment]
With the oidc off its back to where it was before. With oidc on it is not
giving me any tokens

**Comment by chenkie** [comment]
Ok at this point it's probably best to send in a support request. It might be something specific to your account.

**Comment by Steven-Harris** [comment]
Ok, you got a link. I am seeing nothing but articles

**Comment by chenkie** [comment]
Did you check https://support.auth0.com? If you have a plan that comes with support then you can open a ticket. Otherwise you can post something in the community form here: https://community.auth0.com/

**Comment by Steven-Harris** [comment]
Ok I have restarted everything and created a clean copy of the embedded login branch..
I have the follow urls in the "allowed callback" and "allowed cors"
```
http://localhost:4200/#/login, http://localhost:4200/#/callback,
http://localhost:4200/login,
http://localhost:4200/callback,
http://localhost:4200/*
```

I am just getting "Cross origin login not allowed." every time

**Comment by Steven-Harris** [comment]
CORS error is only happening on the custom login and not when using AuthLock

**Comment by chenkie** [comment]
Any other details that come with the error? @luisrudge is there anything you can suggest we try given the cross-origin error?

**Comment by Steven-Harris** [comment]
That is all I can find in the console error. It's not much to go on.

Side note. Using the auth lock I still have the same result with the
access_token. The access token is still not a JWT
