### ISSUE TITLE
Loads of Nonce tokens in Local Storage

### ISSUE THREAD

**Issue by chris31389** [auth0-samples/auth0-angular-samples#35]
Hi,

Is there a safe time to clear Nonce tokens from local storage?  I've got a bit of a build up of them.

Can the request+response remove them after its used?

Thanks,
Chris

**Comment by chenkie** [comment]
It's something that should ultimately be handled by auth0.js. Not sure about a minimum safe time.

We're tracking this issue here if you'd like to follow: https://github.com/auth0/auth0.js/issues/402

**Comment by chenkie** [comment]
Closing this as we're tracking it over at auth0.js
