### ISSUE TITLE
Token Renewal for same server

### ISSUE THREAD

**Issue by chris31389** [auth0-samples/auth0-angular-samples#36]
Hi,

I've just been playing around with the token renewal example and tried to move the silent route to the same server that hosts the main application.  Is there any reason you chose to host it on another server port rather than the same one of the application?

Thanks,
Chris

**Comment by adrianchia** [comment]
I believe it makes it easier for SSO use case where you have app1 and app2 communicate to the same silent route.

**Comment by luisrudge** [comment]
we're moving away from silent auth and using checkSession instead 🎉
