### ISSUE TITLE
npm install fails without --legacy-peer-deps

### ISSUE THREAD

**Issue by HelgeStenstrom** [auth0-samples/auth0-angular-samples#373]
### Checklist

- [X] I have looked into the Readme ([Quickstart sample](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01#readme)/[Standalone sample](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Standalone#readme)) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0-samples/auth0-angular-samples/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I have downloaded the sample-01 repository in two ways, with the same result. First from the Auth0 dashboard at https://manage.auth0.com/dashboard/us/dev-0dbn2nahjvxav1r1/applications/8RRPhe3D9gc8ZtEpcq0tcvewrX781fl3/quickstart, from which I got a zip file sample-01.zip, with m55 sum of e4062e40b5e4d1e00c1d0b422e4f5e7e, and then by cloning this repository.

The npm install command fails with the reported errors according to the console listed a bit further down.

However, `npm install --legacy-peer-deps` succeeds. I get some deprecation warnings, and 10 vulnerabilities (8 moderate, 2 high).

Log from `npm install`:

```
/usr/local/bin/npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @angular/core@15.2.0
npm ERR! Found: zone.js@0.13.0
npm ERR! node_modules/zone.js
npm ERR!   zone.js@"~0.13.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer zone.js@"~0.11.4 || ~0.12.0" from @angular/core@15.2.0
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^15.1.0" from the root project
npm ERR!   peer @angular/core@"15.2.0" from @angular/animations@15.2.0
npm ERR!   node_modules/@angular/animations
npm ERR!     @angular/animations@"^15.2.0" from the root project
npm ERR!     1 more (@angular/platform-browser)
npm ERR!   10 more (@angular/common, @angular/compiler, @angular/forms, ...)
npm ERR! 
npm ERR! Conflicting peer dependency: zone.js@0.12.0
npm ERR! node_modules/zone.js
npm ERR!   peer zone.js@"~0.11.4 || ~0.12.0" from @angular/core@15.2.0
npm ERR!   node_modules/@angular/core
npm ERR!     @angular/core@"^15.1.0" from the root project
npm ERR!     peer @angular/core@"15.2.0" from @angular/animations@15.2.0
npm ERR!     node_modules/@angular/animations
npm ERR!       @angular/animations@"^15.2.0" from the root project
npm ERR!       1 more (@angular/platform-browser)
npm ERR!     10 more (@angular/common, @angular/compiler, @angular/forms, ...)
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/helge/.npm/_logs/2023-06-08T18_29_26_804Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/helge/.npm/_logs/2023-06-08T18_29_26_804Z-debug-0.log

Process finished with exit code 1
```

### Reproduction

1. Download the sample project sample-01.zip, or clone this repository.
2. Go to `auth0-angular-samples/Sample-01` and issue `npm install` in the terminal.
3. Watch the error messages in the terminal window.
4. Issue `npm install --legacy-peer-deps` and watch the command succeed.

My understanding of npm is that "npm install" is run before "npm build" or similar commands. 

### Additional context

I have this software pre-installed:
- MacOS Version 13.4 (22F66)
- node version v18.12.0
- npm version 9.5.0

### Sample

Quickstart

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Thanks, the issue is caused by this PR from dependabot: https://github.com/auth0-samples/auth0-angular-samples/pull/357

I'll provide a fix ASAP, but for now, you should be able to:

- update package.json to use `0.12.0` for zone.js
- remove package-lock.json
- run npm i
