### ISSUE TITLE
TSLint is deprecated by its maintaines.

### ISSUE THREAD

**Issue by HelgeStenstrom** [auth0-samples/auth0-angular-samples#376]
### Checklist

- [X] I have looked into the Readme ([Quickstart sample](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Sample-01#readme)/[Standalone sample](https://github.com/auth0-samples/auth0-angular-samples/tree/master/Standalone#readme)) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0-samples/auth0-angular-samples/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The npm page for TSLint (https://www.npmjs.com/package/tslint) tells that the package is deprecated, and that ESLint should be used instead.

If I remember correctly, Codelyzer is a dependency of TSLint, and is not needed if ESLint is used instead. Codelyzer has a vulnerability, or depends on a vulnerable version of Angular, so it's good if it's not needed.

### Reproduction

1. Look at the npm page for TSLint, and see that it's deprecated by its maintainers.

### Sample

Quickstart

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Thanks for reporting this, I migrated to ESLint in #377
