### ISSUE TITLE
 this.auth0.authorize();

### ISSUE THREAD

**Issue by rannaot** [auth0-samples/auth0-angular-samples#38]
I get an error here - 'Supplied parameters do not match any signature of call target.'

Where the code show function requires, options: AuthorizeOptions

Was the interface changed?

**Comment by chenkie** [comment]
can you show me your call to `authorize`?

**Comment by jclancy93** [comment]
With a call that looks like this: 

    this.auth0.authorize({
      connection: 'google-oauth2',
    });

I get an error saying "Object literal may only specify known properties, and 'connection' does not exist in type 'AuthorizeOptions'."

**Comment by chenkie** [comment]
It looks like the `@types/auth0-js` package is community contributed and only has typings for auth0.js v7. Since they're for v7, this is likely causing issues.

Unfortunately, as of now we don't have plans for officially supported typings.

**Comment by jclancy93** [comment]
@chenkie Its weird cause everything works when I clone the sample app. Its only when I try and implement custom login on my own app (v2.4) that I run into these issues. 

So what do you recommend as a temporary solution? I can get local auth working no problem its only the social connections that are giving me a hard time. Unfortunately am not able to get rid of social login. Should i downgrade to auth0-js v7? Thanks for your quick response.

**Comment by chenkie** [comment]
The samples here don't actually make use of any typings for auth0.js. Does your app have `@types/auth0-js` as a dependency?

**Comment by jclancy93** [comment]
So I think I partially figured out the cause of the problem atleast. My app didn't have an @types/auth0-js dependency, but it had a auth0-lock and a @types/auth0-lock dependency. I was able to set up a new cli project that worked like your sample had intended, so I think the typings from lock might have something to do with it.
