### ISSUE TITLE
http://localhost:3000/#/access_token

### ISSUE THREAD

**Issue by vbenavidesa** [auth0-samples/auth0-angular-samples#39]
There is still an issue on the { useHash: true } parameter with angular 2+, I was wondering if you have a workaround for this case or a next release will fix this issue.

The callback is redirecting to that page due to hash routing in angular.

**Comment by vbenavidesa** [comment]
@chenkie Ok I fixed this by using lock instead of auth0-js, the next issue I am facing after using this is that I get an OK answer with the jwt token, but the setSession and isAuthenticated methods dont seem to be run, as my login button doesnt change for a logout button. Any ideas?

**Comment by chenkie** [comment]
If you'd like to use embedded Lock and you are used hash-based routing, you'll need to use the `resumeAuth` method from Lock to properly process everything. Check out the embedded-login branch and make sure you have a method like [this](https://github.com/auth0-samples/auth0-angular-samples/blob/embedded-login/01-Embedded-Login/src/app/auth/auth.service.ts#L47) specifically.

**Comment by vbenavidesa** [comment]
@chenkie I used that to get the login working, my issue right now is that the OK answer is registered in the logs as "success exchange" and not "success login", and I cant find a place on how to get this working, I get the token, I use the exact same code that you provided.

**Comment by chenkie** [comment]
are your tokens being set into local storage?

**Comment by vbenavidesa** [comment]
For what I am looking at, it seems the resumeAuth() is not executing, no console.log() is being written and I don't see the localStorage being used.

**Comment by chenkie** [comment]
local storage is called in the `setSession` method [here](https://github.com/auth0-samples/auth0-angular-samples/blob/embedded-login/01-Embedded-Login/src/app/auth/auth.service.ts#L67). It sounds like it isn't being reached.

After authentication are you able to see authorization information such as an access token, id token etc in the hash fragment?

**Comment by vbenavidesa** [comment]
I know, but the _setSession_ comes inside the _resumeAuth_ and it is not being reached as you said, I can see the authorization information on the console XHR as a response OK and a JSON object. So it has validated the authorization and given the token. But other than that is not anywhere else.

**Comment by chenkie** [comment]
Are you reaching anything _before_ `resumeAuth` in the `handleAuthenticationWithHash` method?

**Comment by vbenavidesa** [comment]
Nothing it seems, I just had a weird "solved" thing going on with it, I changed it to _auth.handleAuthentication()_ and it is working now, and i do have _{ useHash: true }_ on my router, and it was not working last night with that.

**Comment by chenkie** [comment]
Ok can you let me know if anything changes? `handleAuthenticationWithHash` should be required if you are using hash.

**Comment by vbenavidesa** [comment]
I know, but I switched to _**handleAuthentication**_ just to catch the error I got last night again and it worked, and my actual url looks like this _**http://localhost:5000/#/app/dashboard**_ so it should not work at all. I got kinda confused!
