### ISSUE TITLE
01-Login sample update

### ISSUE THREAD

**Issue by peterblazejewicz** [auth0-samples/auth0-angular-samples#4]
I've to change a code in 01 sample that way:
```diff
diff --git a/01-Login/src/app/auth/auth.service.ts b/01-Login/src/app/auth/auth.service.ts
index 70213f0..68fd9ff 100644
--- a/01-Login/src/app/auth/auth.service.ts
+++ b/01-Login/src/app/auth/auth.service.ts
@@ -8,14 +8,7 @@ declare var Auth0Lock: any;
 @Injectable()
 export class AuthService {
 
-  lock = new Auth0Lock(AUTH_CONFIG.clientID, AUTH_CONFIG.domain, {
-    oidcConformant: true,
-    autoclose: true,
-    auth: {
-      redirectUri: AUTH_CONFIG.callbackURL,
-      responseType: 'token id_token'
-    }
-  });
+  lock = new Auth0Lock(AUTH_CONFIG.clientID, AUTH_CONFIG.domain, {});
```
in order to get it working with social connectors. In fact that is a code implementation from other samples:
https://github.com/auth0-samples/auth0-angularjs2-systemjs-sample/blob/master/01-Login/app/auth.service.ts#L11

Otherwise it does not work with Lock, was this intended?

**Comment by chenkie** [comment]
Hey @peterblazejewicz, this is intentional for use with Lock 10.9. What isn't working?

**Comment by peterblazejewicz** [comment]
@chenkie 
I solved it. The issue goes away if I enable new OAuth 2.0 authorization flow.

https://auth0.com/docs/api-auth/tutorials/configuring-tenant-for-api-auth

I'll make a PR to README.md with note about this so you could decide if it should be included in the docs source or not (yet, it tricked me and there is no yet similar problem on  support forum).
