### ISSUE TITLE
Error: Unsuccessful HTTP response at Request

### ISSUE THREAD

**Issue by lcborn4** [auth0-samples/auth0-angular-samples#42]
I tried running this on my local computer and whenever I try to login I get:

```
Object {original: Error: Unsuccessful HTTP response at Request.<anonymous> (http://localhost:4200/vendor.bundle.js…, statusCode: 401, code: "access_denied", description: "Unauthorized"}
code
:
"access_denied"
description
:
"Unauthorized"
```

the error in the google console is saying: 
`POST https://loganborn.auth0.com/oauth/token 401 ()`

**Comment by chenkie** [comment]
Hi there, which sample are you working from specifically?

**Comment by lcborn4** [comment]
I fixed it by changing the app to a single page application.

I was working on the custom login form sample: 

[(https://github.com/auth0-samples/auth0-angular-samples/tree/embedded-login/02-Custom-Login-Form/src/app)]
