### ISSUE TITLE
Components initialized twice after login

### ISSUE THREAD

**Issue by budilovskiy** [auth0-samples/auth0-angular-samples#43]
Hi. When I'm run sample "02-User-Profile" I have noticed, that CallbackComponent and HomeComponent initialized twice after login. I can't understand this strange behavior.
![image](https://user-images.githubusercontent.com/11961551/28402771-30e649e2-6d2a-11e7-9f3b-84f3c11d9b3e.png)

**Comment by chenkie** [comment]
I've looked at a few possible reasons raised [here](https://stackoverflow.com/questions/38787795/why-ngoninit-called-twice) but none of them seem to be the issue so I'm stumped. Is it causing issues in your app?

**Comment by budilovskiy** [comment]
Hi @chenkie.
It seems that is not a problem with **ngOnInit()**, because the **constructor()** is getting called twice too.
Yes, this causes issues in my app, but I trying to solve the problem, considering this strange behavior.

**Comment by bujardeari** [comment]
@budilovskiy did you fix it?

**Comment by remeezp** [comment]
Hi all, have you managed to fix this.  I am currently experiencing this too.

**Comment by budilovskiy** [comment]
No, unfortunately, I did not solve the problem

**Comment by josephrur** [comment]
Hey guys I found a solution [here](https://www.reddit.com/r/Angular2/comments/6fmzew/canactivate_guard_calls_auth0_if_user_is_not/) look at comments

**Comment by ragavanrajan** [comment]
I have tried commenting the windows.location.hash but no luck. Still the behaviour is same. 
Any help would be appreciated.

**Comment by luisrudge** [comment]
This was fixed in all examples in the latest commit: https://github.com/auth0-samples/auth0-angular-samples/commit/71854b2873f437b013d249bcd53ecb0992bba4a8#diff-c556315f5b572bbf786f8a2aca1076d8L27
