### ISSUE TITLE
Access token must exist to fetch profile

### ISSUE THREAD

**Issue by kartikgreen** [auth0-samples/auth0-angular-samples#44]
I am trying to fetch profile details after login, I get an error Access token must exist to fetch profile. This will work well without errors, if i reload the page

```ts
  ngOnInit() {
        if (this.auth.userProfile) {
          this.profile = this.auth.userProfile;
        }  
        if (this.auth.authenticated) {
            this.auth.getProfile((err, profile) => {
                this.profile = profile;
            });            
        }
    }
```

**Comment by chenkie** [comment]
What does your `getProfile` method look like?

**Comment by kartikgreen** [comment]
Hi,  here is My getProfile method, 
public getProfile(cb): void {
    const accessToken = localStorage.getItem('access_token');
    if (!accessToken) {
      throw new Error('Access token must exist to fetch profile');
    }

    const self = this;
    this.auth0.client.userInfo(accessToken, (err, profile) => {
      if (profile) {
        self.userProfile = profile;
      }
      cb(err, profile);
    });
  }

**Comment by chenkie** [comment]
From what you've described, I would guess that the `getProfile` method is being called before the login transaction fully finishes and there is an access token saved in local storage. Are you able to arrange things so that you can be sure that the access token has been saved before you try to get the profile?

**Comment by kartikgreen** [comment]
here is complete auth service file, please tell me how,
userProfile: Object;
  constructor(private router: Router) {     
  }
  public login(): void {
    this.auth0.authorize();
  } 
  public handleAuthentication(): void {
    this.auth0.parseHash((err, authResult) => {
      if (authResult && authResult.accessToken && authResult.idToken) {
        window.location.hash = '';
        this.setSession(authResult);
        this.router.navigate(['/controlpanel']);
      } else if (err) {
        this.router.navigate(['/controlpanel']);
        console.log(err);
      }
    });
  }
  private setSession(authResult): void {
    console.log("authresult", authResult);
    // Set the time that the access token will expire at
    const expiresAt = JSON.stringify((authResult.expiresIn * 1000) + new Date().getTime());
    localStorage.setItem('access_token', authResult.accessToken);
    localStorage.setItem('id_token', authResult.idToken);
    localStorage.setItem('expires_at', expiresAt);
  }
  public logout(): void {
    // Remove tokens and expiry time from localStorage
    localStorage.removeItem('access_token');
    localStorage.removeItem('id_token');
    localStorage.removeItem('expires_at');
    // Go back to the home route
    this.router.navigate(['/']);
  }
  public getProfile(cb): void {
    const accessToken = localStorage.getItem('access_token');
    if (!accessToken) {
      throw new Error('Access token must exist to fetch profile');
    }

    const self = this;
    this.auth0.client.userInfo(accessToken, (err, profile) => {
      if (profile) {
        self.userProfile = profile;
      }
      cb(err, profile);
    });
  }
  public authenticated(): boolean {
    // Check whether the current time is past the
    // access token's expiry time
    const expiresAt = JSON.parse(localStorage.getItem('expires_at'));
    return new Date().getTime() < expiresAt;
  }

**Comment by kartikgreen** [comment]
Can you please answer me?

**Comment by chenkie** [comment]
Ok let's take a step back with a couple questions:

* Your `ngOnInit` code that you originally showed--is that in a dedicated profile component?
* Can you describe the click steps that would lead to the error? If your implementation follows the sample closely, I would guess that it goes: Load app > log in at Auth0 > get redirected to the home route > click the profile route > get error. Is this correct?
* Before you trigger the error about not having an access token, can you check local storage to see what's there?

**Comment by kartikgreen** [comment]
i followed the tutorial and have implemented same as it is in the documentation.  I want to show the profile  picture , immediately after signing in.

**Comment by chenkie** [comment]
Is the profile image supposed to show up in your `controlpanel` route?

**Comment by kartikgreen** [comment]
in the navbar, so in all pages.

**Comment by chenkie** [comment]
The sample isn't set up to provide the profile to the navbar right away upon successful authentication. The problem is that your navbar is being initialized before authentication completes and the profile is retrieved. It's something that needs to be handled in the Angular app. You'll need to use a different approach and pattern to feed the user profile your navbar to be used after authentication. 

One way you can do this is through an observable and observer. In your AuthService you can set things up like this:

```ts
import { Observable, Observer } from 'rxjs';
// ...
private observer: Observer<string>;
userImageChange$: Observable<string> = new Observable(obs => this.observer = obs);
// ...
public handleAuthentication(): void {
  this.auth0.parseHash((err, authResult) => {
    if (authResult && authResult.accessToken && authResult.idToken) {
      window.location.hash = '';
      this.setSession(authResult);
      this.getProfile();
      this.router.navigate(['/controlpanel']);
    } else if (err) {
      this.router.navigate(['/controlpanel']);
      console.log(err);
    }
  });
}

public getProfile(): void {
  const accessToken = localStorage.getItem('access_token');
  if (!accessToken) {
    throw new Error('Access token must exist to fetch profile');
  }
  const self = this;
  this.auth0.client.userInfo(accessToken, (err, profile) => {
  if (profile) {
      this.observer.next(profile.picture);
    }
  });
}
```

Then in your navbar component you'll want to receive the profile picture after it's retrieved from the `getProfile` call.

```ts
  userImage: string;

  constructor(private auth: AuthService) {}

  ngOnInit() {
    this.auth.userImageChange$.subscribe(image => this.userImage = image);
  }
```

**Comment by phanikumar1223** [comment]
@kartikgreen  I am having the same issue. Are you able to resolve it

**Comment by luisrudge** [comment]
Please check out https://github.com/auth0-samples/auth0-angular-samples/issues/44#issuecomment-318865925 and if this doesn't answer your questions, ping our amazing support team at https://support.auth0.com

**Comment by luije87** [comment]
@phanikumar1223 the solution posted by @chenkie  is partially correct. The issue comes when you refresh the page 'F5'. Just move 'this.getProfile()'
```javascript
public handleAuthentication(): void {
  this.auth0.parseHash((err, authResult) => {
    if (authResult && authResult.accessToken && authResult.idToken) {
      window.location.hash = '';
      this.setSession(authResult);
      //this.getProfile(); <----- incorrect
      this.router.navigate(['/controlpanel']);
    } else if (err) {
      this.router.navigate(['/controlpanel']);
      console.log(err);
    }
    this.getProfile(); // <----- correct
  });
}
```
