### ISSUE TITLE
Usage of scope 'openid profile' is not recommended.

### ISSUE THREAD

**Issue by ayayalar** [auth0-samples/auth0-angular-samples#46]
```
   auth0 = new auth0.WebAuth({
    clientID: 'cli_id'
    domain: 'foo.auth0.com',
    responseType: 'token id_token',
    audience: 'https://foo.auth0.com/userinfo',
    redirectUri: 'http://localhost:4200/callback',
    scope: 'openid profile'
  });
```
Writes out warning `Usage of scope 'openid profile' is not recommended. See https://auth0.com/docs/scopes for more details.` to the console.

In the referred url I didn't find anything specific for this. 

Any idea what is the reason behind this warning?

Thank you

**Comment by chenkie** [comment]
This is a carry over from older usage. The issue is that requesting a `scope` of `profile` will increase the size of the `id_token`. Since the token you'll want to send in requests to your API is the `access_token`, it's not a big deal.

**Comment by ayayalar** [comment]
Thank you for the quick response @chenkie. Then should this warning be removed from the api itself?

**Comment by chenkie** [comment]
np. There may be an issue open for it in the API. I'll follow up on it next week.

**Comment by ayayalar** [comment]
Awesome. I'll close the issue here.

**Comment by mswilson4040** [comment]
Any update on this or link to an issue? I'm getting the same thing and would like to get it out of my console.

**Comment by chenkie** [comment]
I believe it's being looked at right now.

**Comment by MOZGIII** [comment]
Any updates?

**Comment by dboune** [comment]
@chenkie: 

> This is a carry over from older usage.

Does that mean that people who are receiving this message, are also using a deprecated, or no-longer-modern, or what-have-not, method of access?

It's a bit confusing really, referencing various tutorials, pages, example repos -- to tell exactly what is what.

I'm asking because the message is still there after all this time, further adding to the confusion. If it still is an applicable message, what then is the "right" way to request the profile when it is needed?

**Comment by aaguiarz** [comment]
@dboune you should not be getting that warning if you are using auth0.js v9, which is what the Quickstart is using now.

Do you see a different behavior?

**Comment by dboune** [comment]
@aaguiarz: I do.. 

package.json: `"auth0-js": "^9.0.2"`

```
auth0 = new auth0.WebAuth({
    domain: AUTH_CONFIG.domain,
    clientID: AUTH_CONFIG.clientId,
    redirectUri: AUTH_CONFIG.callbackUrl,
    audience: `https://${AUTH_CONFIG.domain}/userinfo`,
    responseType: 'token id_token',
    scope: 'openid profile'
  })
```
Error:
```
cdn.auth0.com/js/lock/10.23.1/lock.min.js:9 Usage of scope 'openid profile' is not recommended. See https://auth0.com/docs/scopes for more details.
```

**Comment by amirhaman** [comment]
Hi, any update on this?

pkg:
`"auth0-js": "^9.4.2"`

Auth:
```
private _auth0 = new auth0.WebAuth({
    clientID: AUTH_CONFIG.CLIENT_ID,
    domain: AUTH_CONFIG.CLIENT_DOMAIN,
    responseType: 'token id_token',
    redirectUri: AUTH_CONFIG.REDIRECT,
    audience: AUTH_CONFIG.AUDIENCE,
    scope: AUTH_CONFIG.SCOPE
});
```

err:
`lock.min.js:9 Usage of scope 'openid profile' is not recommended.`

Thanks

**Comment by lk-jeffpeck** [comment]
Still happening in 9.6.0

**Comment by aaguiarz** [comment]
That message was removed from Lock 11. 

You are probably using Lock 10 in the Hosted Login Page.

Regards,

Andres
