### ISSUE TITLE
Api-Server.js in Standalone project does not show error message when audience has not been set

### ISSUE THREAD

**Issue by IanTaite** [auth0-samples/auth0-angular-samples#466]
### Checklist

- [X] I have looked into the Readme ([Quickstart sample](https://github.com/auth0-samples/auth0-angular-samples/tree/main/Sample-01#readme)/[Standalone sample](https://github.com/auth0-samples/auth0-angular-samples/tree/main/Standalone#readme)) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0-samples/auth0-angular-samples/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I've been trying to follow the standalone components tutorial, and I don't know what I'm supposed to enter for `authorizationParams.audience` in auth_config.json.

I noticed that api_server.js should output an error if the audience parameter has not been set.

The default value for audience is "{API_IDENTIFIER}" but api_server.js checks for "YOUR_API_IDENTIFIER", so it looks like the error message will never be shown.

I'm proposing that in api_server.js, this:

```
if (
  !authConfig.domain ||
  !authConfig.authorizationParams.audience ||
  authConfig.authorizationParams.audience === "YOUR_API_IDENTIFIER"
) {
  console.log(
    "Exiting: Please make sure that auth_config.json is in place and populated with valid domain and audience values"
  );

  process.exit();
}
```
be changed to
```
if (
  !authConfig.domain ||
  !authConfig.authorizationParams.audience ||
  authConfig.authorizationParams.audience === "{API_IDENTIFIER}"
) {
  console.log(
    "Exiting: Please make sure that auth_config.json is in place and populated with valid domain and audience values"
  );

  process.exit();
}
```

### Reproduction

Step 1.

Don't replace the audience value in auth_config.json

Step 2.

run `npm run dev1

Step 3.

Notice that the error message `"Exiting: Please make sure that auth_config.json is in place and populated with valid domain and audience values"` is not shown.

Step 4.

Control+C to kill the API and frontend processes

Step 5.

Make the code change I've suggested to api_server.js

Step 6.

Repeat step 2.

Step 7.

Notice the error message appears.

### Additional context

Node 18.13.0
NPM 8.19.3
Angular CLI 17.0.5
Git repo: https://github.com/auth0-samples/auth0-angular-samples.git
Git branch: main

### Sample

Standalone

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Thanks for reporting. It's a bit more complicated, and we realy need to check for `YOUR_API_IDENTIFIER `, especially when you download the sample as part of the quickstart.

However, we should probably also check for the value we configured in the env file, so:

```
["YOUR_API_IDENTIFIER", "{API_IDENTIFIER}"].includes(authConfig.authorizationParams.audience)
```

Would that solve the problem in your situation and show the error accordingly?
