### ISSUE TITLE
Explanation of Audience in ReadMe and How to Create An API In Auth0 Needed

### ISSUE THREAD

**Issue by IanTaite** [auth0-samples/auth0-angular-samples#469]
### Checklist

- [X] I have looked into the Readme ([Quickstart sample](https://github.com/auth0-samples/auth0-angular-samples/tree/main/Sample-01#readme)/[Standalone sample](https://github.com/auth0-samples/auth0-angular-samples/tree/main/Standalone#readme)) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0-samples/auth0-angular-samples/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

In the "Auth0 Configuration for the Sample Application(s)" section of the ReadMe, the instructions state that (I paraphrase) "The example application(s) require to be configured with your Auth0 information to run successfully. This can be done by replacing {DOMAIN}, {CLIENT_ID} and {API_IDENTIFIER} with your tenant-specific values in auth_config.json."

With regard to API_IDENTIFIER, this explanation/instruction is too vague.

As a beginner using Auth0 for the first time, it is not at all clear what the API_IDENTIFIER is or where I would get the value. The above instructions imply it's from within the Auth0 settings where DOMAIN and CLIENT_ID are located, whereas in fact for this demo repo, in the Auth0 Dashboard,

- You create an application, and the application has a DOMAIN and a CLIENT_ID.
- You also create an API. As part of that process, you would add an Identifier and as the prompt states, (this is a) "Unique identifier for the API. This value will be used as the audience parameter on authorization calls."

It seems the API is the source of the API_IDENTIFIER value to be entered in auth_config.json, but nowhere does it state that you have to create one to be able to get this value.

I've spent almost all of today on this, and for want of better/clearer instructions my time would not have been wasted.

### Describe the ideal solution

The ideal solution would be for the ReadMe notes to be _clearer_ about what it takes to get a value for API_IDENTIFIER so that no one else wastes time discovering this for themselves.

### Alternatives and current workarounds

I honestly hope I've not overlooked something. If I should have gone elsewhere to gain this "prior knowledge", or the "prior knowledge" could be alluded to by linking to it in the read me then that might also do.

### Additional context

n/a

**Comment by frederikprijck** [comment]
Hey, a question I have here is if you looked at our sample in isolation, or where you following https://auth0.com/docs/quickstart/spa/angular/ ?

Our sample is a sample that's for that quickstart in particular. If you go to that link, login and download the sample, everything is filled in for you.

**Comment by IanTaite** [comment]
Hi there,

I'm not having a very good dev experience at the moment.

I'm specifically looking for a demo project that uses Standalone
Components, preferably Angular 17, preferably with interceptors, with
protected and public routes, and automatic token refresh.

When I try to download the (pre-configured) sample, I'm getting a HTTP 400
error, posting to https://auth0.com/docs/package/v2. I think this example
just does login and logout though.

I've spent a bit of today wondering why there are two repos:
https://github.com/auth0-sample and https://github.com/auth0-developer-hub

I've looked at the example code from the
https://github.com/auth0-developer-hub/spa_angular_typescript_hello-world_standalone-components
repository. I'm on the basic-authentication branch but I can't get this to
work. The authentication seems to work, but on return to my Angular app, I
see "Error" in the UI, and the dev tools shows a POST request to
https://dev-a3avq8wrrkXXXXXX.uk.auth0.com/oauth/token that fails with a 401
error. Within the Auth0 dashboard under Monitoring Logs, I see two
messages, one is a Success Login and the later message is a Failed Exchange
message.

**Comment by frederikprijck** [comment]
> When I try to download the (pre-configured) sample, I'm getting a HTTP 400
error, posting to https://auth0.com/docs/package/v2. I think this example
just does login and logout though.

Apologies, I broke something while renaming the master branch to main in this samples repository, and a fix is underway to get that resolved. So even thought my elaboration on the automatic configuring is typically true, for the Angular Samples it will work again once the fix is deployed, sorry about that.

> I've spent a bit of today wondering why there are two repos:
https://github.com/auth0-sample and https://github.com/auth0-developer-hub

I am not involved with the auth0-developer-hub, and it's not maintained by the team that builds and maintains the SDK. The Auth0-Samples is.

> I'm not having a very good dev experience at the moment.

Please let me know where I can help, as that is definetly not our intention and we always try to improve were possible.

**Comment by frederikprijck** [comment]
Reopening, merging the PR closes this while I believe we are still discussing things.

**Comment by frederikprijck** [comment]
Downloading the sample on the Quickstart works as expected now, apologies, that one was on me.

Closing as it is fixed now, and the experience should be better. Feel free to reach out when things can still be improved.

**Comment by deanbiltup** [comment]
Why was this ticket close? I 100% agree that the documentation here "https://github.com/auth0-samples/auth0-angular-samples" says enter the info like I have it AND worse I just signed in.  this should be re-opened and just add to the docs a few steps on how to create an api token OR link to doc on how I am supposed to do this @frederikprijck please please!   I got some zip file and none of mine was filled in like the post implied so then looking at readme and that is not showing how to do this api piece.  I am still poking around but the doc/README should be updated so people that end up with an app with not filled in values have a path forward.  I have a few guesses I may try but I will try that spa link first.

**Comment by deanbiltup** [comment]
lmao, I tried out https://auth0.com/docs/quickstart/spa/angular/ ? and it gave me eveerything filled in EXCEPT audience and left that as     "audience": "{yourApiIdentifier}". - grrrrrrrr, some docs on this api stuff would be great.  I am going to have to do some guessing from my google oauth knowledge of doing this :( .

**Comment by deanbiltup** [comment]
For next person (but this was me guessing  so not 100% - links to how to add audience and use or have example not require audience - I do not know why the example requires an audience - it failed server startup if no audience as I tried deleeting it)
 
1. creating an api called basic, identifier https://basic.company.com and jwt profile auth0, signing rs256
2. in your client, click api tab and give access to this new api
3. modify config file to have identifier https://basic.company.com
4. npm install
5. npm run build
6. npm run prod

**FAIL :(  me crying :( ** -> 

at least the server started -> 

App server listening on port 4200
Api started on port 3001
GET / 404 8.062 ms - 139
GET / 404 2.111 ms - 139
GET / 404 5.422 ms - 139

**Comment by deanbiltup** [comment]
I got one more step working 'npm run dev' works while 'npm run build, npm run prod' does not work.

npm run dev working -> but login failed :( . 

I get 

An error was returned from Auth0
Something went wrong when trying to authorize your application. Please inspect the error below and ensure auth_config.json is configured correctly.

Unauthorized

**I am stumped, working with google oauth previously, they gave information as to issues in the console server or client depending **.  I have no info from auth0 clients here :( to continue debugging myself.
