### ISSUE TITLE
Not able to access user_metadata through profile component

### ISSUE THREAD

**Issue by toddler4372** [auth0-samples/auth0-angular-samples#47]
I'm able to access a few of the user attributes such as the picture:
`<img src="{{profile?.picture}}" class="profile-avatar-lg">`
But when I try and get any of the user_metadata:
`<h2 class="p-b-10">{{ profile?.user_metadata.first_name }} {{ profile?.user_metadata.last_name }}</h2>`
I get an error:
**`ERROR TypeError: Cannot read property 'first_name' of undefined`**

Is my syntax wrong?

**Comment by toddler4372** [comment]
Could I get an answer to this?

I tried also to expose the user_metadata with a rule:

```
 function (user, context, callback) {
   var namespace = 'https://dev-lecra-services.eu.auth0.com/';
   context.idToken = context.idToken || {};
   console.log("context.idToken before : " + JSON.stringify(context.idToken));
   context.accessToken = context.accessToken || {};
   if (user.user_metadata) {
     context.idToken[namespace + 'user_metadata'] = user.user_metadata;
   }
   if (user.app_metadata) {
     context.idToken[namespace + 'app_metadata'] = user.app_metadata;
   }
   console.log("context.idToken after : " + JSON.stringify(context.idToken));
 
   callback(null, user, context);
 }
```

But I still get the same error.

**Comment by chenkie** [comment]
You won't be able to get `user_metadata` in your profile object. This was previously possible by requesting `user_metadata` as a `scope` when authenticating, but isn't supported in the latest pipeline.

If you'd like to get items from `user_metadata` in a custom claim in your `id_token`, you'll need to ask for them by name. For example:

```js
context.idToken[namespace + 'foo'] = user.user_metadata.bar;
```

**Comment by toddler4372** [comment]
Thanks for the reply. I put this rule into the dash:
```
function (user, context, callback) {
  var namespace = 'https://myapp.example.com/';
  context.idToken[namespace + 'first_name'] = user.user_metadata.first_name;
  callback(null, user, context);
}
```
and when I try to retrieve:
`{{ user.user_metadata.first_name }}`
I still get the error:
`ERROR TypeError: Cannot read property 'user_metadata' of undefined`

Do you see something I'm missing?

**Comment by chenkie** [comment]
Sorry, I should have clarified. The `user_metadata` object isn't going to end up in the profile object your get from calling `userInfo()`. That rule will, however, put the `first_name` property in your `id_token`. You can use this in your app by decoding the token and reading it from the payload. Use **jwt-decode** for this.

```bash
npm i --save jwt-decode
```
```ts
import decode from 'jwt-decode';
// ...
idTokenPayload: any = decode(localStorage.getItem('id_token'));
console.log(idTokenPayload['https://myapp.example.com/first_name']);
```

It's not clear from your code if this is what you're doing already or not, but if it isn't, give it a shot.

**Comment by toddler4372** [comment]
I installed jwt-decode and now have this as my profile.component.ts:
```
import { Component, ViewEncapsulation, OnInit } from '@angular/core';
import { AuthService } from './../auth/auth.service';
import { Location } from '@angular/common';
import decode from 'jwt-decode';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class ProfileComponent implements OnInit {

  profile: any;
  idTokenPayload: any = decode(localStorage.getItem('id_token'));

  constructor(public auth: AuthService, private location: Location) {
    
  }

  ngOnInit() {
    if (this.auth.userProfile) {
      this.profile = this.auth.userProfile;
    } else {
      this.auth.getProfile((err, profile) => {
        this.profile = profile;
      });
    }
    console.log(this.idTokenPayload['https://myapp.example.com/first_name']);
  }
  
  goBack() {
    this.location.back(); 
  }

}
```
In the console I just get "undefined."

**Comment by toddler4372** [comment]
I also updated the rule to show my actual local URL. Is that a problem?
```
function (user, context, callback) {
  var namespace = 'http://localhost:4200/';
  context.idToken[namespace + 'first_name'] = user.user_metadata.first_name;
  callback(null, user, context);
}
```

**Comment by chenkie** [comment]
Are you sure that you have your `id_token` in local storage when your component initializes? One thing you can try is console.logging the whole decoded payload in the `ngOnInit` method to see what you get and to make sure your custom claim is there. You should also decode your token at https://jwt.io to see the payload.

The namespace you use in the rule doesn't matter, it just needs to be something that is unique to you.

**Comment by toddler4372** [comment]
Can you give me the console.log command for the whole payload?

**Comment by toddler4372** [comment]
When running `console.log(this.idTokenPayload);` this is what I got:

```
{name: "Todd Williams", given_name: "Todd", family_name: "Williams", nickname: "toddlerwilliams", picture: "https://lh3.googleusercontent.com/-tyOuwONL83o/AAAAAAAAAAI/AAAAAAAAWtI/iMcl1947cgk/photo.jpg", …}
at_hash
:
"M36u3KSP4NHSxjJAC43zAw"
aud
:
"BNWgmHi4Ton3xd7sLKlXygFhQgzsWhe6"
exp
:
1503025989
family_name
:
"Williams"
gender
:
"male"
given_name
:
"Todd"
iat
:
1502989989
iss
:
"https://buddi-health.auth0.com/"
locale
:
"en"
name
:
"Todd Williams"
nickname
:
"toddlerwilliams"
nonce
:
"hDpA68ekL~AJaxx820Kvl3uS2bDiuVS4"
picture
:
"https://lh3.googleusercontent.com/-tyOuwONL83o/AAAAAAAAAAI/AAAAAAAAWtI/iMcl1947cgk/photo.jpg"
sub
:
"google-oauth2|114987429743136878040"
updated_at
:
"2017-08-17T17:13:09.231Z"
```

**Comment by toddler4372** [comment]
To answer your earlier question, I'm seeing the id_token in Local Storage before I navigate to /profile.

**Comment by toddler4372** [comment]
It's showing up now, Ryan. I can see now in the console that it's picking up 'faveColor' from the metadata. 
`console.log(this.idTokenPayload['http://localhost:4200/faveColor']);` returns `blue`
However, I still get the error:
`ERROR TypeError: Cannot read property 'user_metadata' of undefined`
when I try to access it in the profile view:
`{{ user.user_metadata.faveColor }}`

Anything look wrong to you?

**Comment by chenkie** [comment]
Where are you trying to access `user` in that fashion? Can you show me the code?

If it's in your Angular app that you're trying to access `user_metadata` on the `user` object, I assume that it's what was previously called `profile` in your opening post. If that's the case, then presumably this object is being populated by [this call](https://github.com/auth0-samples/auth0-angular-samples/blob/master/02-User-Profile/src/app/auth/auth.service.ts#L48) to `auth0.client.userInfo`. You won't be able to get the `user_info` object back from this call. Auth0 won't put `user_info` onto that object.

**Comment by toddler4372** [comment]
In my profile.component.html being called from profile.component.ts.  That code is here:
```
import { Component, ViewEncapsulation, OnInit } from '@angular/core';
import { AuthService } from './../auth/auth.service';
import { Location } from '@angular/common';
import decode from 'jwt-decode';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class ProfileComponent implements OnInit {

  profile: any;
  idTokenPayload: any = decode(localStorage.getItem('id_token'));

  constructor(public auth: AuthService, private location: Location) {
    
  }

  ngOnInit() {
    if (this.auth.userProfile) {
      this.profile = this.auth.userProfile;
    } else {
      this.auth.getProfile((err, profile) => {
        this.profile = profile;
      });
    }
    console.log(this.idTokenPayload['http://localhost:4200/faveColor']);
    console.log(this.idTokenPayload);
  }
  
  goBack() {
    this.location.back(); 
  }

}
```
I'm only using `user` because I saw that in the documentation.  Previously in my AngularJS app I had used:
`{{ profile.user_metadata.faveColor }}`

**Comment by chenkie** [comment]
So the reason you don't get `user_metadata` on the `profile` object is because Auth0 doesn't populate it there. That's why you'll want to use custom claims on your `id_token`. So from your profile page (or wherever) you can do `{{ idTokenPayload.faveColor }}`

**Comment by toddler4372** [comment]
Ok, I see. I gave `<span>{{ idTokenPayload.faveColor }}</span>` a shot and the span is just empty. Weird. `Blue` still shows up in the console with the command `console.log(this.idTokenPayload['http://localhost:4200/faveColor']);` however.

**Comment by chenkie** [comment]
well you'd need to assign the property that exists on `idTokenPayload['http://localhost:4200/faveColor']` to `idToken.faveColor` to make that work. Auth0 is going to place the `faveColor` property on your `id_token` on a property called `['http://localhost:4200/faveColor']` because that's the instruction in your rule. So the options in your Angular app are:

```html
<span>{{ idTokenPayload['http://localhost:4200/faveColor'] }}</span>
```

or you can assign that property to something easier in your component.

```ts
import { Component, ViewEncapsulation, OnInit } from '@angular/core';
import { AuthService } from './../auth/auth.service';
import { Location } from '@angular/common';
import decode from 'jwt-decode';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.css'],
  encapsulation: ViewEncapsulation.None
})
export class ProfileComponent implements OnInit {

  profile: any;
  idTokenPayload: any = decode(localStorage.getItem('id_token'));

  // ...

  ngOnInit() {
    if (this.auth.userProfile) {
      this.profile = this.auth.userProfile;
    } else {
      this.auth.getProfile((err, profile) => {
        this.profile = profile;
      });
    }
   this.idTokenPayload.faveColor = this.idTokenPayload['http://localhost:4200/faveColor']);
  }
  // ...
}
```

Then you would be able to do `<span>{{ idTokenPayload.faveColor }}</span>` in your template.

**Comment by toddler4372** [comment]
I'm understanding it now. Thanks a lot! It works now.

**Comment by chenkie** [comment]
no prob

**Comment by dylanwoo** [comment]
Is there a php example of this?
