### ISSUE TITLE
Uncaught Error: Can't resolve all parameters for AuthService: (?).

### ISSUE THREAD

**Issue by mayordwells** [auth0-samples/auth0-angular-samples#51]
I have this very confusing error and I have no idea what to ask google. 
I am using auth0 on an angular + rails app to help with authentication between a Shopify App in Rails and the front end of the app in Angular, I am using webpacker. The rails app currently works with Shopify but we are currently working a separate interface on the front end in angular in.
When I remove AuthService from the providers array in app modeul everything works fine. 
But when AuthService is available in providers array, I am getting this error: 
My AuthService is exactly same as what I found in the documentation and git commit.

Please help me out.
Here's what my AuthService parameters look like:
```
auth0 = new auth0.WebAuth({
    clientID: AUTH_CONFIG.clientID,
    domain: AUTH_CONFIG.domain,
    responseType: 'token id_token',
    audience: `https://${AUTH_CONFIG.domain}/userinfo`,
    redirectUri: 'http://localhost:5000/callback',
    scope: 'openid'
  });
```
Currently, when I authenticate with Rails, Everything works fine. But once we work the redirect to angular app. The session is lost.
How can we get the session parameters/request parameters from rails in my angular 4 app.

**Comment by luisrudge** [comment]
Hi, looks like you're having some issues integrating your app with Auth0. This repo is made of angular samples that work out of the box. If you're still seeing issues with your own code, please reach out to our amazing support team at https://support.auth0.com

If you find any issues with this repo specifically, please open a new issue with the proper reproduction steps. Thanks 🎉
