### ISSUE TITLE
ERROR TypeError: Cannot read property 'split' of null at AuthService.webpackJsonp.25.AuthService.userHasScopes (auth.service.ts:91)  

### ISSUE THREAD

**Issue by Jscott388** [auth0-samples/auth0-angular-samples#53]
Can't figure this out. I downloaded directly with configuration already set, did npm install and started.

**Comment by chenkie** [comment]
I just tried the same and wasn't able to reproduce. Can you check local storage after login to see if you have anything for `scope` in there?

**Comment by Jscott388** [comment]
Fixed. I been using different quick starts. So I had a token stored still when I fired up a new quick start.
