### ISSUE TITLE
Angular 2+ Login: Outdated auth0-js dependency

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-angular-samples#54]
Seeds projects are using an oudated version of the dependency auth0-js
Latest auth0-js version 8.9.2

![image](https://user-images.githubusercontent.com/26749061/30893263-3f81be7a-a30b-11e7-9284-92ff0418b94e.png)

**Comment by luisrudge** [comment]
we'll upgrade them 🎉
