### ISSUE TITLE
Minor: LICENSE file is misspelled in source.

### ISSUE THREAD

**Issue by mpiroc** [auth0-samples/auth0-angular-samples#56]
The correct spelling is "LICENSE", not "[LICENCE](https://github.com/auth0-samples/auth0-angular-samples/blob/master/LICENCE)"

**Comment by chenkie** [comment]
Looks like GH is ok with either :)

<img width="94" alt="screen shot 2017-10-02 at 1 46 23 pm" src="https://user-images.githubusercontent.com/1847678/31091183-243a9f58-a778-11e7-92b1-5f8564e72c60.png">

It is probably best if we fix it for consistency. Would you like to send in a PR?
