### ISSUE TITLE
Cannot match any routes. URL Segment: 'access_token'

### ISSUE THREAD

**Issue by QLaille** [auth0-samples/auth0-angular-samples#57]
I pretty much followed the entire quickstart/login part of [Angular2+ Auth0](https://auth0.com/docs/quickstart/spa/angular2/01-login), and stopped at the part where it says that `
This example assumes you are using the default Angular path-based routing. If you are using hash-based routing with { useHash: true }, you will not be able to specify a dedicated callback route. The URL hash will be used to hold the user's authentication information.` I'm using a hash-based routing, so I thought we could had more info on that page, but no.

I kept following this tutorial until I had in my devtool the ` Error: Cannot match any routes. URL Segment: 'access_token'`.

Then I just researched what I could possibly do, and found the [handleAuthenticationWithHash](https://github.com/auth0-samples/auth0-angular-samples/blob/embedded-login/01-Embedded-Login/src/app/auth/auth.service.ts#L47) sample, so I changed everything to match it.

Unfortunately, the error is still here, the funny part is I still have the correct access_token and id_token in my localStorage, and when refreshing, my login button disappear so I'm basically logged in, what am I possibly doing wrong ?

Edit : 

I'm using auth0-js 8.10.1, augnlar 4.2.4 and angular-cli 1.4.2

**Comment by chenkie** [comment]
The `handleAuthenticationWithHash` method is for use with Lock.js. Unfortunately when you use auth0.js, the authentication result must come back on the hash fragment.

The error you're getting is because Angular tries to match a route called `access_token`. As far as I know, there isn't a way to avoid this.

Out of curiosity, is there a reason in particular that you don't want to use path-based routing?

**Comment by QLaille** [comment]
Well, the gitlab server isnt in my hands, so when it comes to refreshing any page of my apps the server is confused because it doesnt know the exact route, but angular does, so in the meantime I'm using hash-based routing, so I guess my issue is kinda "resolved" because it is unrelated.

**Comment by vishwanathsunkari** [comment]
hey did you solve the issue ? please let me know the solution

**Comment by sathishkumarkk** [comment]
@chenkie Do you have a solution fo this issue or what is your advice.
