### ISSUE TITLE
Wrong apiUrl and Audience parameter in Angular2 sample projects.

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-angular-samples#63]
When download the Sample project, the parameter apiUrl in:
 \03-calling-an-api\src\app\auth\auth0-variables.ts 
\05-token-renewal\src\app\auth\auth0-variables.ts
\04-authorization\src\app\auth\auth0-variables.ts
Variable AUDIENCE in \04-authorization\.env

are not propely prepopulated.

For example, I'm logged in a tenant in Australia region, and no matter how many times I reload the page, clean the cookies, close and open the windows, and download the project again, the apiUrl parameter still shows the audience from the European region tenant.

I've tried changing tenant within the same region and it appear to be ok, but when I try with my AU or US tenants, it is stuck with the EU URL.

AUTH-3348

**Comment by aaguiarz** [comment]
Yes, API Urls are not correctly set in any Quickstart, we are working on a solution for it.

**Comment by luisrudge** [comment]
closing because it's not related to the repo itself
