### ISSUE TITLE
Wrong handling of invalid fields during signup

### ISSUE THREAD

**Issue by rafanog** [auth0-samples/auth0-angular-samples#69]
The handling of the blank fields during user registration has three details:
 - If the password's left blank:
![image](https://user-images.githubusercontent.com/15782359/33176700-588e2c16-d036-11e7-9d2d-dfead97e403a.png)

- Using an invalid email:
![image](https://user-images.githubusercontent.com/15782359/33176793-b1e2b444-d036-11e7-8975-c1a281c71bc3.png)

 - If you put some info on the fields, then delete them before triggering signup:
![image](https://user-images.githubusercontent.com/15782359/33176855-eace2270-d036-11e7-9d12-56358e535c8f.png)

**Comment by luisrudge** [comment]
Hi, this appear to be a Lock issue. Can you open the issue in that repo with the proper repro steps? Thanks! https://github.com/auth0/lock/
