### ISSUE TITLE
Unnecessary dependency to auth0.js library in silent.html

### ISSUE THREAD

**Issue by andreasgrimm** [auth0-samples/auth0-angular-samples#72]
There's an unnecessary dependency to the `auth0.js` library and unnecessary configuration in the `silent.html` file.

The current version of the library handles it just fine if from the iFrame you just post the hash to the parent:
```js
parent.postMessage({
      hash: window.location.hash,
      type: 'auth0:silent-authentication'
    }, 'http://localhost:4200');
```

#71 simplifies the silent authentication.
What do you think?

**Comment by luisrudge** [comment]
we're moving away from silent auth 🎉

**Comment by musclor** [comment]
Hi @luisrudge 

My concern with checkSession is that it requires to set the "Allowed Web Origins" in the Clients settings which does not support http://localhost:4200

So I cannot test it on my local machine.

Would you have a solution for that, please ?

**Comment by aaguiarz** [comment]
Hi @musclor 

That url should be supported in Allowed Web Origins, please try again.

Thanks,

Andres

**Comment by musclor** [comment]
Hi @aaguiarz 

I have just tried again and I confirm that it works now. 

Thank you for telling me that the url should work otherwise I would have always thought it does not. I can now serenely move away from renewAuth() and silent.html 👍

**Comment by andreasgrimm** [comment]
are the examples waiting for _auth0.js_ v9 to be released?

**Comment by luisrudge** [comment]
@andreasgrimm nope. I'm finishing the examples right now (they all work with 8.latest).
