### ISSUE TITLE
Rxjs version throws error when navigating

### ISSUE THREAD

**Issue by jitterbugboy** [auth0-samples/auth0-angular-samples#73]
The rxjs version from the package is outdated as i uses  5.4.2 this throws an error "EmptyError: no elements in sequence"
when navigating to profile and other sections.
update package.json to latest 5.5.4 seems to solve the issue

**Comment by luisrudge** [comment]
do you know why that's the case? any stacktrace or something?

**Comment by luisrudge** [comment]
I just cloned the repo and it works. I'm adding a few changes, to the repo. Try again after I push everything. THanks 🎉
