### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Amialc** [auth0-samples/auth0-angular-samples#8]
When I'm trying to log in using username-password-authentication, I received `401 Unauthorized`, but I'm sure that credentials is correct.
![image](https://cloud.githubusercontent.com/assets/1114365/22439920/1824087a-e73a-11e6-9c5a-1395d3876511.png)
Also when I'm trying to use google-oauth2 connection, it logs my `Success login` with different email but in reality nothing happens, I'm still having `You are not logged in! Please Log In to continue.` (other social connections works simmilar, logs my `Success login`, but nothing happens on client)
![image](https://cloud.githubusercontent.com/assets/1114365/22439965/452e3d18-e73a-11e6-8446-d1694ef00037.png)

**Comment by peterblazejewicz** [comment]
@Amialc if that is not related to code implementation error, first try dev forums:
https://ask.auth0.com/

**Comment by chenkie** [comment]
Closing this as it's likely not related to these samples.

**Comment by elnobun** [comment]
@Amialc have you resolved this? I am having the same issue.

**Comment by zilions** [comment]
Also having the same issue
