### ISSUE TITLE
SPA Angular2 (Docker): Login Sample not running

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-angular-samples#83]
After using sh exec.sh and show that the compilation was a success, when trying to run the sample in the browser show an error "Invalid Host header".

This happen only in the 01-Login sample.

![screenshot_1](https://user-images.githubusercontent.com/15818783/34614726-ccd52982-f208-11e7-82f8-848f06bb8e0a.jpg)
![screenshot_2](https://user-images.githubusercontent.com/15818783/34614727-ccfc2af0-f208-11e7-89fb-7395e71bd4fd.jpg)

**Comment by aaguiarz** [comment]
Can you try using 127.0.0.1 or localhost?

**Comment by paulioceano** [comment]
It was not possible to run this using 127.0.0.1 or localhost. But Re-try using http://192.168.99.100:3000 and worked fine
