### ISSUE TITLE
04-Authorization fails to compile

### ISSUE THREAD

**Issue by wcraytor** [auth0-samples/auth0-angular-samples#90]
04-Authorization compile ends with errors:
ERROR in src/app/admin/admin.component.ts(22,8): error TS2339: Property 'map' does not exist on type 'Observable<Response>'.
src/app/auth/auth.service.ts(17,27): error TS2339: Property 'apiUrl' does not exist on type 'AuthConfig'.
src/app/ping/ping.component.ts(25,24): error TS2339: Property 'json' does not exist on type 'Object'.
src/app/ping/ping.component.ts(40,24): error TS2339: Property 'json' does not exist on type 'Object'.

Similar story for 03-calling-an-api  

Doesn't anyone update these examples?  Most of them have never worked since the 4 years I have been checking in on Auth0.  You would think by now they would be perfect.  Far from it.

**Comment by aaguiarz** [comment]
Hi @wcraytor 

I apologize for the inconveniences. 

We do have a process for testing each PR, but we didn't do the right thing with a change merged a couple of days before your reported this. 

We should have answered you 2 weeks ago, we also failed at that.

On the good news side, we are fixed the issue yesterday in this commit .https://github.com/auth0-samples/auth0-angular-samples/pull/92, and we are adding automation to all Quickstarts so these things don't happen anymore https://circleci.com/gh/auth0-samples/auth0-angular-samples

Regards,

Andres
